futhark.cabal
src/Futhark/CodeGen/ImpGen.hs
src/Futhark/CodeGen/KernelImpGen.hs
src/Futhark/Construct.hs
src/Futhark/ExpandArrays.hs
src/Futhark/ExplicitAllocations.hs
src/Futhark/Externalise.hs
src/Futhark/ExtractKernels/Distribution.hs
src/Futhark/FirstOrderTransform.hs
src/Futhark/Internalise.hs
src/Futhark/Interpreter.hs
src/Futhark/KernelBabysitting.hs
src/Futhark/Optimise/DoubleBuffer.hs
src/Futhark/Optimise/InPlaceLowering/SubstituteIndices.hs
src/Futhark/Optimise/Simplifier/Rules.hs
src/Futhark/Passes.hs
src/Futhark/Representation/AST/Attributes.hs
src/Futhark/Representation/AST/Attributes/Ranges.hs
src/Futhark/Representation/AST/Attributes/TypeOf.hs
src/Futhark/Representation/AST/Pretty.hs
src/Futhark/Representation/AST/Syntax.hs
src/Futhark/Representation/AST/Traversals.hs
src/Futhark/Tools.hs
src/Futhark/TypeCheck.hs
src/futhark-opencl.hs
src/futhark.hs

This brings us within a factor of three compared to Cosmins LocVolCalib!

Array expansion and improved coalescing

---

docs/language-reference.rst

Don't double double

---

data/tests/default-keyword/float.fut
data/tests/vasicek/iobound-mc2.fut
src/Language/Futhark/Parser/Lexer.x
src/Language/Futhark/Parser/Parser.y
src/Language/Futhark/Parser/Tokens.hs

Adding a `float` keyword

---

data/tests/vasicek/iobound-mc2.fut
src/Language/Futhark/Parser/Lexer.x
src/Language/Futhark/Parser/Parser.y
src/Language/Futhark/Parser/Tokens.hs

for now, implemented as nullary functions
@Athas

const, closes #123

---

tools/README.md
tools/futhark.lang

Some functions may still appear as keywords.

Created Gedit/GtkSourceView syntax highlighter for Futhark.

---

rts/c/opencl.h
src/futhark-opencl.hs

This compiles fine for me on OSX. Travis-CI should confirm it can still compile fine on Linux.

Fix for OSX

---

src/Futhark/CodeGen/ImpGen/Kernels.hs
src/Futhark/Pass/ExpandAllocations.hs
src/Futhark/Pass/ExplicitAllocations.hs
src/Futhark/Pass/ExtractKernels/BlockedKernel.hs
src/Futhark/Pass/KernelBabysitting.hs
src/Futhark/Representation/Kernels/Kernel.hs
src/Futhark/Representation/Kernels/Simplify.hs

This is to support scanomap.
Seems to work.

Modify scan kernel to have two lambdas.

---

docs/language-reference.rst
src/Futhark/Compiler.hs
src/Futhark/Internalise.hs
src/Language/Futhark/Attributes.hs
src/Language/Futhark/Parser.hs
src/Language/Futhark/Parser/Lexer.x
src/Language/Futhark/Parser/Parser.y
src/Language/Futhark/Pretty.hs
src/Language/Futhark/Renamer.hs
src/Language/Futhark/Syntax.hs
src/Language/Futhark/TypeChecker.hs

Merge this to add the type aliasing feature to Futhark

finished working on type aliasing

---

docs/windows-installation.rst

Now that I've gotten more comfortable with the command line and no longer using Github Desktop, this seems like a natural change to make.

Forking the repository is not necessary.

---

src/Futhark/MonadFreshNames.hs
src/Futhark/Optimise/CSE.hs
src/Futhark/Optimise/Fusion/LoopKernel.hs
src/Futhark/Representation/ExplicitMemory.hs
src/Futhark/Representation/Kernels/Kernel.hs
src/Futhark/Representation/SOACS/Simplify.hs
src/Language/Futhark/Attributes.hs
src/Language/Futhark/Pretty.hs
src/Language/Futhark/Renamer.hs

No stack integration yet, but it'll get there.

GHC 8 support

---

appveyor.yml

Does not actually run the compiler yet, merely checks that it builds.  It's a start.

Windows-based CI

---

data/tests/distribution/irregular0.fut
data/tests/soacs/reduce5.fut
src/Futhark/Analysis/Rephrase.hs
src/Futhark/CodeGen/ImpCode.hs
src/Futhark/CodeGen/ImpCode/Kernels.hs
src/Futhark/CodeGen/ImpGen.hs
src/Futhark/CodeGen/ImpGen/Kernels.hs
src/Futhark/Optimise/CSE.hs
src/Futhark/Optimise/DoubleBuffer.hs
src/Futhark/Optimise/Simplifier/Engine.hs
src/Futhark/Optimise/Simplifier/Lore.hs
src/Futhark/Pass/CoalesceMemoryAccesses.hs
src/Futhark/Pass/ExpandAllocations.hs
src/Futhark/Pass/ExplicitAllocations.hs
src/Futhark/Pass/ExtractKernels/BlockedKernel.hs
src/Futhark/Pass/KernelBabysitting.hs
src/Futhark/Representation/AST/Pretty.hs
src/Futhark/Representation/ExplicitMemory.hs
src/Futhark/Representation/Kernels/Kernel.hs
src/Futhark/Representation/Kernels/Simplify.hs
src/Futhark/TypeCheck.hs
src/Futhark/Util/Pretty.hs

This is somewhat more complicated, but it will hopefully let us
perform some nice optimisations, including block tiling.  At the
moment, only ReduceKernels have been replaced with the new system.

Introduce new kernel representation.  #103-related.

---

src/Futhark/Representation/Kernels/KernelExp.hs

Doing a pull request for this seems silly, but I still wanted your acceptance ;)

Document the KernelExp Combine.

---

src/Futhark/CodeGen/ImpGen/Kernels/ToOpenCL.hs
src/Futhark/CodeGen/OpenCL/Kernels.hs

New transpose

---

rts/python/panic.py
rts/python/reader.py
src/Futhark/CodeGen/Backends/GenericPython.hs
src/Futhark/CodeGen/Backends/GenericPython/Definitions.hs
src/Futhark/CodeGen/Backends/PyOpenCL.hs
src/Futhark/CodeGen/Backends/SequentialPython.hs

Make Python programs able to read binary input

---

futlib/math.fut
tests/futlib/math.fut

floor, ceil, trunc, and round operations for f64 and f32 modules

---

src/Futhark/CodeGen/ImpGen.hs
src/Futhark/Optimise/DoubleBuffer.hs
src/Futhark/Optimise/InPlaceLowering.hs
src/Futhark/Optimise/Simplifier/Rules.hs
src/Futhark/Pass/ExplicitAllocations.hs
src/Futhark/Pass/ExtractKernels.hs
src/Futhark/Pass/ExtractKernels/BlockedKernel.hs
src/Futhark/Pass/ExtractKernels/Distribution.hs
src/Futhark/Pass/MemoryBlockMerging/ArrayCoalescing.hs
src/Futhark/Representation/AST/Attributes/Names.hs
src/Futhark/Representation/AST/Attributes/Scope.hs
src/Futhark/Representation/AST/Traversals.hs
src/Futhark/Representation/Kernels/KernelExp.hs
src/Futhark/TypeCheck.hs

We will also need some package updates eventually - that will be fun.

Modifications for GHC 8.2 support.

---

src/Futhark/Test.hs

I would like to use this feature.  Is it okay?

Allow multiple structure tests.

---

rts/c/values.h
rts/python/reader.py

This finishes up the work for https://github.com/diku-dk/futhark/issues/382

Support hexadecimal floats in Python and C reader.

---

docs/man/futhark-c.rst
docs/man/futhark-opencl.rst
rts/c/opencl.h
rts/c/panic.h
rts/c/timing.h
src/Futhark/Actions.hs
src/Futhark/CodeGen/Backends/COpenCL.hs
src/Futhark/CodeGen/Backends/COpenCL/Boilerplate.hs
src/Futhark/CodeGen/Backends/GenericC.hs
src/Futhark/CodeGen/Backends/GenericC/Options.hs
src/Futhark/CodeGen/Backends/SequentialC.hs
src/Futhark/CodeGen/Backends/SimpleRepresentation.hs
src/Futhark/CodeGen/ImpCode.hs
src/Futhark/Representation/Primitive.hs
src/futhark-c.hs
src/futhark-opencl.hs
src/futhark.hs

Error handling is still very crude.

Add --library flag to futhark-c and futhark-opencl.

---

docs/language-overview.rst
docs/language-reference.rst
src/Futhark/Doc/Generator.hs
src/Futhark/Internalise/Bindings.hs
src/Futhark/Internalise/TypesValues.hs
src/Language/Futhark/Attributes.hs
src/Language/Futhark/Parser/Parser.y
src/Language/Futhark/Pretty.hs
src/Language/Futhark/Syntax.hs
src/Language/Futhark/TypeChecker.hs
src/Language/Futhark/TypeChecker/Terms.hs
src/Language/Futhark/TypeChecker/Types.hs

Remove old-style shape annotations.

---

src/Futhark/Internalise.hs
src/Futhark/Internalise/Bindings.hs
src/Futhark/Internalise/TypesValues.hs
src/Language/Futhark/Attributes.hs
src/Language/Futhark/TypeChecker/Terms.hs
src/Language/Futhark/TypeChecker/Types.hs
tests/errors/duplicate-params.fut
tests/errors/duplicate-vars.fut
tests/shapes/shape-annot-is-param.fut

Permit size annotations to refer to earlier parameters.

---

CHANGELOG.md
docs/language-reference.rst
futlib/math.fut
src/Language/Futhark/Parser/Parser.y
tests/distribution/icfp16-example.fut
tests/range0.fut
tests/range1.fut
tests/range2.fut

Remove brackets around array ranges.

---

src/Futhark/Internalise/Defunctionalise.hs
tests/higher-order-functions/issue493.fut

Proper handling of closed-over dynamic functions in defunctionalizer.

---

src/Futhark/Internalise/Monomorphise.hs
src/Language/Futhark/Attributes.hs
src/Language/Futhark/TypeChecker/Terms.hs
tests/operator/section0.fut
tests/operator/section1.fut

Permit operator sections everywhere.

---

src/Futhark/Internalise/Defunctionalise.hs
tests/higher-order-functions/binop0.fut
tests/higher-order-functions/binop1.fut
tests/higher-order-functions/binop2.fut

Defunctionalization of higher-order infix operators.

---

docs/versus-other-languages.rst

Fixes to the text.
Maybe also add a section about "more to read" at the end with pointers to the basis library and link to documentation about SOACs and modules.

versus-other-languages update

---

src/Language/Futhark/TypeChecker/Terms.hs
tests/shapes/negative-position-shape0.fut
tests/shapes/negative-position-shape1.fut
tests/shapes/negative-position-shape2.fut
tests/shapes/negative-position-shape3.fut

Shape parameters must be used in a positive position first.

---

src/Futhark/Construct.hs
src/Futhark/Interpreter.hs
src/Futhark/Optimise/Fusion.hs
src/Futhark/Optimise/Fusion/Composing.hs
src/Futhark/Optimise/Fusion/LoopKernel.hs
src/Futhark/Pass/ExpandAllocations.hs
src/Futhark/Pass/ExtractKernels.hs
src/Futhark/Pass/ExtractKernels/BlockedKernel.hs
src/Futhark/Pass/ExtractKernels/Kernelise.hs
src/Futhark/Pass/ExtractKernels/Segmented.hs
src/Futhark/Representation/SOACS/SOAC.hs
src/Futhark/Representation/SOACS/Simplify.hs
src/Futhark/Tools.hs
src/Futhark/Transform/FirstOrderTransform.hs
tests/unused-reduce.fut

Similarly for scanomap.
This is a simplification that is also hopefully one step on the path
to a greater unification of our SOACs.

Change redomap fold function to a map function.

---

src/Futhark/Internalise/Defunctionalise.hs

This optimization to the defunctionalizer will omit (nested) empty closure environments from the records constructed for lambda-abstractions and it will omit either of `e1'` and `e2'` in an application if they only represent empty closure environments. It also avoids lifting functions that only capture empty environments.
This makes the defunctionalized programs significantly more readable and it could possibly improve compilation times. Do we have any good benchmark programs to evaluate compilation times?

Omit empty closure environments from defunctionalized programs.

---

futlib/sobol.fut
tests/futlib/random_pi.fut
tests/futlib/sobol_pi.fut

Maybe we should rename the function to something else than `redomap`?

Alternative sobol reducer using higher-order functions

---

tools/futhark-autotune

Introduced domain-specific knowledge about threshold-comparisons and branching structure of the different code-versions to optimize the auto-tuner. This leads to much faster auto-tuning, as the tuner only tries configurations, that result in new code-versions being executed.
BA-project.

added domain-specific knowledge to the auto-tuner

---

futlib/sobol.fut

Even simpler sobol interface...

Simple sobol interface

---

src/Futhark/Test.hs

Makes PR #574 a bit nicer! 
Edit: I suspect that the `E.evaluate` call is not necessarily sufficient to catch all errors since it only [evaluates to WHNF](https://hackage.haskell.org/package/base-4.11.1.0/docs/Control-Exception.html#g:8); my understanding of `ByteString` is a bit shallow (it's possible that a `force` is needed from `DeepSeq`).

Adds filename reporting/graceful failure for corrupt/invalid .gz input files

---

CHANGELOG.md
docs/usage.rst
rts/c/lock.h
src/Futhark/CodeGen/Backends/COpenCL/Boilerplate.hs
src/Futhark/CodeGen/Backends/GenericC.hs
src/Futhark/CodeGen/Backends/SequentialC.hs

Make API functions thread safe.

---

docs/conf.py
docs/index.rst
docs/man/futhark-pkg.rst
docs/package-management.rst
package.yaml
src/Futhark/Pkg/Info.hs
src/Futhark/Pkg/Solve.hs
src/Futhark/Pkg/Types.hs
src/futhark-pkg.hs
stack-lts-9.2.yaml
unittests/Futhark/Pkg/SolveTests.hs
unittests/futhark_tests.hs

Relevant to #592.
I do not claim that this implementation is finished.  In particular, I suspect that its error handling is too naive, some logging would be nice, and I think there's a wart or two left in the solver.  However, I believe the design is sound, there is a decent amount of documentation, and it is ready for human trials.

Add draft version of futhark-pkg.

---

package.yaml
unittests/Futhark/Analysis/ScalExpTests.hs
unittests/Futhark/Optimise/AlgSimplifyTests.hs
unittests/Futhark/Pkg/SolveTests.hs
unittests/Futhark/Representation/AST/Attributes/RearrangeTests.hs
unittests/Futhark/Representation/AST/Attributes/ReshapeTests.hs
unittests/Futhark/Representation/AST/Attributes/ValuesTests.hs
unittests/Futhark/Representation/AST/AttributesTests.hs
unittests/Futhark/Representation/AST/Syntax/CoreTests.hs
unittests/Futhark/Representation/PrimitiveTests.hs
unittests/Language/Futhark/SyntaxTests.hs
unittests/futhark_tests.hs

The latter is newer and more well-maintained.

Migrate from test-framework to tasty.

---

src/Futhark/CodeGen/ImpGen/Kernels/ToOpenCL.hs
src/Futhark/CodeGen/OpenCL/Kernels.hs

They now all take the same parameters.

Regularise the transposition kernels.

---

CHANGELOG.md
futlib/math.fut
rts/csharp/scalar.cs
rts/python/scalar.py
src/Futhark/CodeGen/Backends/SimpleRepresentation.hs
src/Futhark/Representation/Primitive.hs
src/Futhark/Util.hs
tests/primitive/gamma.fut
tests/primitive/lgamma.fut

Add gamma and lgamma functions.

---

src/Futhark/CodeGen/ImpGen/Kernels.hs
src/Futhark/CodeGen/ImpGen/Kernels/Base.hs
src/Futhark/CodeGen/ImpGen/Kernels/SegRed.hs
src/Futhark/Optimise/TileLoops.hs
src/Futhark/Pass/ExtractKernels/BlockedKernel.hs
src/Futhark/Pass/ExtractKernels/Intragroup.hs
src/Futhark/Pass/KernelBabysitting.hs
src/Futhark/Representation/Kernels/Kernel.hs
src/Futhark/Representation/Kernels/Simplify.hs

Restrict parallelism of map kernels to hardware parallelism.

---

README.md

I found this book on /r/futhark, and saw that it isn't linked to from anywhere I could see (the README or the website), thought to add it here.

Adds link to Parallel Programming in Futhark book

---

tools/png2data.py

Add png2data tool

---

src/Futhark/CLI/Autotune.hs

Also supports having no `main` function.
Fixes #830

Support multiple entry points when auto tuning

---

src/Futhark/Representation/ExplicitMemory.hs

While working on another feature, I accidentally generated ExplicitMemory code where there were too many context parameters in the pattern matching of a loop, like this:
```
let {i32 size_4105, i32 b_ixfn_4145, mem b_mem_4146;
[size_4105]i32 b_4106} =
loop {i32 loop₁_4107, mem b_mem_4141;
[loop₁_4107]i32 b_4108} = {10i32, mem_4140, res_4104}
for i_4109:i32 < n_4102 do {
...
in {m_4114, mem_4144, loopres_4119}
}
```
This wasn't caught by the ExplicitMemory type checker, because the context was not checked against the return type of the expressions in `matchPatternToExp`. This PR is supposed to fix that.

Verify that all context parameters are used in the return type

---

src/Futhark/Representation/ExplicitMemory.hs

Verify that the number of existentials in the index function matches the number
of context results

Add additional type check in matchReturnType

---

docs/man/futhark-bench.rst
src/Futhark/Bench.hs
src/Futhark/CLI/Autotune.hs
src/Futhark/CLI/Bench.hs
src/Futhark/CodeGen/Backends/GenericC.hs

This fixes the static arrays stuff.

Multicore merge

---

src/Futhark/CodeGen/Backends/MulticoreC.hs

With this change, the Futhark ray tracer works with the multicore backend.  And it's actually the second-fastest CPU implementation, by a significant margin!

Fix multicore backend for programs that contain safety checks.

---

CHANGELOG.md
run-tests.sh
src/Futhark/CLI/Test.hs

Don't output tty control codes if the terminal is dumb

---

CHANGELOG.md
src/Futhark/Bench.hs
src/Futhark/CLI/Autotune.hs
src/Futhark/CLI/Bench.hs
src/Futhark/CLI/Test.hs
src/Futhark/CodeGen/Backends/GenericC.hs
src/Futhark/CodeGen/Backends/GenericPython.hs
src/Futhark/Util.hs

Disabled when output is insufficiently fancy.
Closes #996.

'futhark bench': print progress bar for each dataset.

---

CHANGELOG.md
rts/c/cuda.h
src/Futhark/CLI/CUDA.hs
src/Futhark/CodeGen/Backends/CCUDA.hs
src/Futhark/CodeGen/Backends/CCUDA/Boilerplate.hs
src/Futhark/CodeGen/Backends/COpenCL.hs
src/Futhark/CodeGen/Backends/COpenCL/Boilerplate.hs

Profile GPU events in CUDA backend.

---

CHANGELOG.md
src/Futhark/CodeGen/Backends/GenericC.hs
src/Futhark/CodeGen/ImpCode.hs
src/Futhark/CodeGen/ImpGen/Kernels/ToOpenCL.hs
tests/noinline/noinline0.fut
tests/noinline/noinline1.fut
tests/noinline/noinline2.fut
tests/noinline/noinline3.fut
tests/noinline/noinline4.fut

Still quite limited.
Closes #1016.

Support function calls in device code.

---

src/Futhark/Analysis/Alias.hs
src/Futhark/Analysis/UsageTable.hs
src/Futhark/IR/Aliases.hs
src/Futhark/IR/KernelsMem.hs
src/Futhark/IR/Mem/Simplify.hs
src/Futhark/IR/Prop/Names.hs
src/Futhark/IR/SOACS/Simplify.hs
src/Futhark/IR/SeqMem.hs
src/Futhark/Optimise/InPlaceLowering.hs
src/Futhark/Optimise/Simplify/Engine.hs
src/Futhark/Optimise/Simplify/Lore.hs
src/Futhark/Pass/ExplicitAllocations.hs
src/Futhark/TypeCheck.hs

This replaces an old ad-hoc mechanism with one that is more
principled.  It is faster, too.

Track sizes in usage table.

---

src/Language/Futhark/Parser/Lexer.x

This PR cleans up the lexer, making it shorter, more correct, and IMO more readable.
Previously, the lexer failed to lex hexadecimal float literals like `0xabc.def321p0f32` that were type suffixed, but also contain the hex digit sequence `f32` or `f64` beforehand.  This is fixed.
Edit: `happy` does not seem to be very happy in the CI... not sure why

Clean up lexer and fix bug

---

docs/language-reference.rst
src/Futhark/Actions.hs
src/Futhark/CLI/C.hs
src/Futhark/CLI/CUDA.hs
src/Futhark/CLI/OpenCL.hs
src/Futhark/CLI/PyOpenCL.hs
src/Futhark/CLI/Python.hs
src/Futhark/CLI/Test.hs
src/Futhark/CodeGen/Backends/CCUDA.hs
src/Futhark/CodeGen/Backends/COpenCL.hs
src/Futhark/CodeGen/Backends/PyOpenCL.hs
src/Futhark/CodeGen/Backends/SequentialC.hs
src/Futhark/CodeGen/Backends/SequentialPython.hs
src/Futhark/CodeGen/ImpGen.hs
src/Futhark/CodeGen/ImpGen/CUDA.hs
src/Futhark/CodeGen/ImpGen/Kernels.hs
src/Futhark/CodeGen/ImpGen/OpenCL.hs
src/Futhark/CodeGen/ImpGen/Sequential.hs
src/Futhark/Compiler.hs
src/Futhark/Compiler/CLI.hs
src/Futhark/IR/Prop.hs
src/Futhark/IR/Syntax.hs
src/Futhark/Internalise/Monad.hs
src/Futhark/Optimise/InliningDeadFun.hs
src/Language/Futhark/Warnings.hs
tests/attributes/warn_on_safety_checks0.fut
tests/attributes/warn_on_safety_checks1.fut
tests/attributes/warn_on_safety_checks2.fut

Add warn(safety_checks) attribute for warning on bounds checks.

---

CHANGELOG.md
src/Futhark/CLI/REPL.hs
src/Futhark/CLI/Run.hs
src/Language/Futhark/Interpreter.hs

Add :unbreak command to futhark repl.

---

futhark.cabal
src/Futhark/Analysis/Metrics.hs
src/Futhark/CodeGen/ImpGen/Multicore.hs
src/Futhark/IR/Kernels/Simplify.hs
src/Futhark/IR/MC.hs
src/Futhark/IR/MC/Op.hs
src/Futhark/IR/MCMem.hs
src/Futhark/IR/SOACS/Simplify.hs
src/Futhark/Internalise.hs
src/Futhark/Optimise/CSE.hs
src/Futhark/Optimise/InPlaceLowering.hs
src/Futhark/Optimise/Simplify.hs
src/Futhark/Optimise/Simplify/Rules.hs
src/Futhark/Optimise/Sink.hs
src/Futhark/Optimise/Unstream.hs
src/Futhark/Pass/ExpandAllocations.hs
src/Futhark/Pass/ExplicitAllocations/MC.hs
src/Futhark/Pass/ExtractKernels/ToKernels.hs
src/Futhark/Pass/ExtractMulticore.hs
src/Futhark/Transform/FirstOrderTransform.hs
src/Futhark/Transform/Rename.hs
tests/inplace-replicate.fut
tests/soacs/stream0.fut

Remember to read the email first.

Multicore multiversion

---

rts/python/opencl.py
src/Futhark/CodeGen/Backends/COpenCL/Boilerplate.hs
src/Futhark/CodeGen/Backends/GenericPython.hs
src/Futhark/CodeGen/Backends/GenericPython/AST.hs
src/Futhark/CodeGen/Backends/PyOpenCL/Boilerplate.hs
src/Futhark/CodeGen/OpenCL/Heuristics.hs

This permits values to be a function of some device property.

Let OpenCL heuristics be expressions.

---

CHANGELOG.md
prelude/math.fut
rts/python/scalar.py
src/Futhark/CodeGen/Backends/SimpleRep.hs
src/Futhark/IR/Primitive.hs
tests/primitive/ctz.fut

Implement ctz intrinsic.

---

src/Futhark/CodeGen/Backends/GenericPython.hs

This fix is for improved error message handling for the python library when futhark is compiled into a python library. Specifically for a more descriptive error message when dtypes do not match.
An example futhark program
```futhark
entry select(db : [][]i32) (col : i32) : []i32 =  db[:, col]
```
And corresponding library call from a python program 
```python
import numpy as np
from db import db
data = np.array([[1, 2, 3, 4]])
instance = db()
result =  instance.select(data, 3)
print(result)
```
Then compiled and run
```
futhark python --library db.fut && python3 fut_call_example.py
Traceback (most recent call last):
File "fut_call_example.py", line 6, in <module>
result =  instance.select(data, 3)
File "/Users/philiplassen/CS/FutDB/db.py", line 1365, in select
db_mem_36_ext))
TypeError: …
```

More descriptive error messages when dtypes are wrong for the Python backend

---

src/Futhark/Actions.hs
src/Futhark/CLI/C.hs
src/Futhark/CLI/CUDA.hs
src/Futhark/CLI/Dev.hs
src/Futhark/CLI/OpenCL.hs

Turn C compilation backends into Actions.

---

src/Futhark/Pass/ExtractMulticore.hs

Instead we depend on sequentialisation to generate efficient code.
**Do benchmark carefully after pulling!** This is basically just a different kind of heuristic.  It looked a good bit faster on the benchmarks I tried.

Do not perform flattening in multicore pipeline.

---

src/Futhark/CodeGen/Backends/GenericPython.hs

This fix catches a possible missed error in the Python backend. The error is when the dimensionality of the array expected by futhark does not match the dimension of the numpy array given as an arguement.  Below is a toy example.
An example futhark program
```futhark
entry select(db : [][]i32) (col : i32) : []i32 =  db[:, col]
```
And corresponding library call from a python program 
```python
import numpy as np
from db import db
data = np.array([1, 2, 3, 4]).astype(np.int32)
instance = db()
result =  instance.select(data, 3)
print(result)
```
Then compiled and run
```
futhark python --library db.fut && python3 fut_call_example.py
Traceback (most recent call last):
File "fut_call_example.py", line 6, in <module>
result =  instance.select(data, 3)
File "/Users/philiplassen/CS/FutDB/db.py", …
```

Raise Error on dimension mismatch

---

CHANGELOG.md
docs/language-reference.rst
src/Futhark/CodeGen/ImpGen.hs
src/Futhark/Internalise.hs
src/Futhark/Optimise/Simplify/Rules.hs
tests/attributes/unroll0.fut
tests/attributes/unroll1.fut
tests/attributes/unroll2.fut

Add #[unroll] attribute.

---

.github/workflows/main.yml
tools/oclgrindrunner.sh

Run OpenCL code through oclgrind on CI.

---

CHANGELOG.md
docs/man/futhark-cuda.rst
libtests/c/Makefile
libtests/c/f.fut
libtests/c/test_f.c
src/Futhark/CodeGen/Backends/CCUDA.hs
src/Futhark/CodeGen/Backends/CCUDA/Boilerplate.hs
src/Futhark/CodeGen/Backends/GenericC.hs
src/Futhark/CodeGen/ImpGen/Kernels/ToOpenCL.hs

CUDA backend can now be called from multiple threads.

---

src/Futhark/CodeGen/ImpGen.hs
src/Futhark/CodeGen/ImpGen/Kernels.hs
src/Futhark/CodeGen/ImpGen/Kernels/Base.hs
src/Futhark/CodeGen/ImpGen/Kernels/SegHist.hs
src/Futhark/CodeGen/ImpGen/Kernels/SegMap.hs
src/Futhark/CodeGen/ImpGen/Kernels/SegRed.hs
src/Futhark/CodeGen/ImpGen/Kernels/SegScan.hs

These will help us keep our types straight, hopefully.

Introduce typed variables in code generator

---

tools/README.md

I was going through the tools and figuring out what some of them did. I though I might as well add a synopsis of some of the tools in the README.md. I didn't get to all of them, but I think I got the ones that are likely most useful.

Add some documentation for Tools

---

CHANGELOG.md
src/Futhark/Optimise/TileLoops.hs
tests/tiling/tiling_1d_partial.fut
tests/tiling/tiling_2d_partial.fut

Implement partial tiling.

---

CHANGELOG.md
docs/man/futhark-c.rst
docs/man/futhark-cuda.rst
docs/man/futhark-multicore.rst
docs/man/futhark-opencl.rst
docs/usage.rst
src/Futhark/Actions.hs

Respect CC and CFLAGS.

---

rts/c/timing.h

Deletes the dead code in timing.h.

Remove dead code in timing.h

---

src/Futhark/Internalise/Defunctionalise.hs
tests/shapes/hof0.fut
tests/shapes/hof1.fut

Fixes #1158.
Hopefully won't have too many bugs.  We're *really* pushing the
defunctionaliser now.

Size-preserving defunctionalisation.

---

src/Futhark/Internalise/Defunctionalise.hs

Defunctionalisation improvements

---

rts/c/values.h

I expect the '-t' option is broken, however.

Fix the handling of stdin/stdout.

---

CHANGELOG.md
docs/conf.py
docs/index.rst
docs/man/futhark-script.rst
docs/man/futhark.rst
futhark.cabal
src/Futhark/CLI/Autotune.hs
src/Futhark/CLI/Bench.hs
src/Futhark/CLI/Check.hs
src/Futhark/CLI/Dataset.hs
src/Futhark/CLI/Dev.hs
src/Futhark/CLI/Doc.hs
src/Futhark/CLI/Pkg.hs
src/Futhark/CLI/REPL.hs
src/Futhark/CLI/Run.hs
src/Futhark/CLI/Script.hs
src/Futhark/CLI/Test.hs
src/Futhark/Compiler/CLI.hs
src/Futhark/Script.hs
src/Futhark/Server.hs
src/Futhark/Test/Values.hs
src/Futhark/Util/Options.hs
src/Futhark/Util/Pretty.hs
src/futhark.hs

Here is an example of a FutharkScript program:
```
-- # The Example
--
-- Welcome to my great Futhark program!
--
-- Check out this shit:
entry fact (n: i32) = i32.sum (1...n)
-- Cool, right?
--
-- Now dig this:
-- :res fact 10i32
-- And it can get even fancier:
entry mkimg (h: i64) (w: i64) =
tabulate_2d h w (\i j -> u32.f64 ((f64.i64 (i*j) / f64.i64 (h*w))*255))
-- :img mkimg 100i64 300i64
-- We can also do advanced data analysis.
entry analysis (n: i64) =
unzip (tabulate n (\i -> (f64.i64 i, f64.sqrt (f64.i64 i))))
-- :plot2d<500,200> analysis 100i64
```
Which produces this: https://sigkill.dk/junk/example.html

Futharkscript

---

CHANGELOG.md
prelude/math.fut

We'll merge this shortly before the next release.  This function is rarely used anyway.

Rename negate to neg.

---

src/Futhark/IR/SOACS/SOAC.hs
src/Futhark/Pass/ExtractKernels.hs
src/Futhark/Pass/ExtractKernels/DistributeNests.hs
src/Futhark/Pass/ExtractKernels/Intragroup.hs
src/Futhark/Pass/ExtractMulticore.hs
src/Futhark/Transform/FirstOrderTransform.hs

Also refactored some of the code used when further processing scatters.

Better scatter docs

---

docs/man/futhark-literate.rst
src/Futhark/CLI/Literate.hs

Interpret byte-arrays (u8) as greyscale images

---

docs/man/futhark-literate.rst
shell.nix
src/Futhark/CLI/Literate.hs
tests_literate/expected/img.md
tests_literate/img.fut

Also add a basic test for images in futhark literate.

Support boolean images as black-and-white in futhark literate

---

examples/lotka_volterra.fut

Added example with Lotka Volterra equations and two basic numerical integrators (Euler method and Runge-Kutta).

Added example with lotka volterra equations

---

src/Futhark/CodeGen/Backends/CCUDA.hs
src/Futhark/CodeGen/Backends/COpenCL.hs
src/Futhark/CodeGen/Backends/COpenCL/Boilerplate.hs

Output size-comparison logging information on CUDA

---

cabal.project
default.nix
futhark.cabal
nix/versions.nix
src/Futhark/Pkg/Types.hs
stack.yaml

Switch to versions 5.

---

prelude/math.fut

Add machine epsilon for floating point types.

---

src/Futhark/Optimise/Sink.hs
tests/sinking5.fut

This provides (much) better sinking with deeply nested conditionals.

Better sinking.

---

src/Futhark/CLI/Bench.hs
src/Futhark/CLI/Test.hs
src/Futhark/Util.hs

Cap dataset description name at 40 chars

---

CHANGELOG.md
docs/language-reference.rst
src/Futhark/Internalise.hs
src/Futhark/Internalise/Defunctionalise.hs
src/Futhark/Internalise/FreeVars.hs
src/Futhark/Internalise/Monomorphise.hs
src/Language/Futhark/Interpreter.hs
src/Language/Futhark/Parser/Parser.y
src/Language/Futhark/Pretty.hs
src/Language/Futhark/Query.hs
src/Language/Futhark/Syntax.hs
src/Language/Futhark/Traversals.hs
src/Language/Futhark/TypeChecker/Terms.hs
src/Language/Futhark/TypeChecker/Types.hs
tests/shapes/letshape0.fut
tests/shapes/letshape1.fut
tests/shapes/letshape10.fut
tests/shapes/letshape2.fut
tests/shapes/letshape3.fut
tests/shapes/letshape7.fut
tests/shapes/letshape8.fut
tests/shapes/letshape9.fut

Add size binding in `let` expressions.

---

src/Futhark/CLI/Autotune.hs

If the sampling run fails, we should truly return "no information". Currently,
we return `(tMin, tMax)`, but if this is the first dataset we're tuning, and the
sample run fails, we should return `Nothing`. Then, if the collective result of
tuning a threshold is `Nothing`, we should use `thresholdMin` to select the
alternative code version. Hopefully, that won't fail.
Fixes #1336

Handle failing sample runs correctly

---

CHANGELOG.md
src/Language/Futhark/TypeChecker/Terms.hs
tests/higher-order-functions/uniqueness2.fut
tests/higher-order-functions/uniqueness3.fut
tests/higher-order-functions/uniqueness4.fut
tests/sumtypes/sumtype21.fut
tests/sumtypes/sumtype24.fut
tests/uniqueness/uniqueness-error0.fut
tests/uniqueness/uniqueness-error1.fut
tests/uniqueness/uniqueness-error11.fut
tests/uniqueness/uniqueness-error21.fut
tests/uniqueness/uniqueness-error26.fut
tests/uniqueness/uniqueness-error3.fut
tests/uniqueness/uniqueness-error4.fut
tests/uniqueness/uniqueness-error47.fut
tests/uniqueness/uniqueness-error54.fut
tests/uniqueness/uniqueness-error55.fut
tests/uniqueness/uniqueness-error6.fut
tests/uniqueness/uniqueness-error7.fut
tests/uniqueness/uniqueness-error8.fut
tests/uniqueness/uniqueness-error9.fut
tests/uniqueness/uniqueness54.fut

Fix handling of nameless aliases.

---

CHANGELOG.md
prelude/math.fut
rts/python/scalar.py
src/Futhark/CodeGen/Backends/SimpleRep.hs
src/Futhark/IR/Primitive.hs
tests/primitive/hypot.fut

Add f32.hypot, f64.hypot.

---

src/Futhark/Optimise/ReuseAllocations.hs

Do not merge memory blocks across nested segops

---

src/Futhark/Analysis/Interference.hs

We conservatively treat all memory arguments to a DoLoop to interfere
with each other, as well as anything used inside the loop.  This could
potentially be improved by looking at the interference computed by the
loop body wrt. the loop arguments, but probably very few programs
would benefit from this.

Improve interference tracking of loop memory parameters.

---

src/Futhark/CodeGen/ImpCode.hs
src/Futhark/CodeGen/ImpGen/GPU.hs
src/Futhark/CodeGen/SetDefaultSpace.hs
src/Futhark/Optimise/DoubleBuffer.hs
src/Futhark/Pass/ExpandAllocations.hs
tests/doublebuffer.fut

Goal is to avoid a copy per iteration of the loop.  We'll see whether it actually works.

Better double buffering

---

rts/javascript/wrapperclasses.js

Wasm free check

---

.github/workflows/main.yml
tests_lib/javascript/Makefile
tests_lib/javascript/a.fut
tests_lib/javascript/package.json
tests_lib/javascript/test_a.js

Finally got a test set up sort of working with ES6, for library tests with Node.
Let me know if this setup is the kind of thing you had in mind. If so I'll start populating with tests that tests meaningful functionality.

Initial setup for WASM/JS Node library tests

---

tests_lib/javascript/Makefile
tests_lib/javascript/array.fut
tests_lib/javascript/test_array.js

Some library tests for arrays with JS/WASM backend in Node

Add array library tests for JS/Node.

---

.github/workflows/main.yml
tests_lib/web/Makefile
tests_lib/web/jest-puppeteer.config.js
tests_lib/web/package.json
tests_lib/web/square.fut
tests_lib/web/square.html
tests_lib/web/square.test.js

This is what I managed to whip up for the web tests, to address #1406.
I'll try and add some more tests over time.
Any feedback would be appreciated. I'm still pretty green with respect to Node and web testing.

Initial web tests

---

rts/javascript/values.js

This checks to make sure the data being read, matches the types `restore` expects.

Add typename checking to values.js.

---

src/Futhark/CodeGen/ImpGen.hs
src/Futhark/IR/Mem/IxFun.hs

Only insert copy if index functions are not equivalent

---

.github/workflows/main.yml
CHANGELOG.md
docs/c-api.rst
docs/manifest.schema.json
docs/usage.rst
futhark.cabal
shell.nix
src/Futhark/Actions.hs
src/Futhark/CodeGen/Backends/GenericC.hs
src/Futhark/CodeGen/Backends/GenericC/CLI.hs
src/Futhark/CodeGen/Backends/GenericC/Manifest.hs
src/Futhark/CodeGen/Backends/GenericC/Server.hs
src/Futhark/CodeGen/Backends/SimpleRep.hs
tests_lib/c/Makefile
tests_lib/c/validatemanifest.py

Generate manifest files.

---

src/Futhark/IR/Mem/Simplify.hs

This simplification causes problems with the short-circuiting pass, and doesn't improve performance for any benchmarks.

Remove removeIdentityCopy

---

src/Language/Futhark/Warnings.hs

WIP links:
[futhark-language-server](https://github.com/haoranpb/futhark-language-server)
[vscode-futhark](https://github.com/haoranpb/vscode-futhark)

Export Warnings for language server

---

src/Futhark/CLI/Defs.hs
src/Futhark/CLI/Misc.hs
src/Futhark/Compiler/Program.hs
src/Futhark/Util.hs
src/Language/Futhark/Prop.hs
src/Language/Futhark/TypeChecker.hs
src/Language/Futhark/TypeChecker/Terms/Monad.hs

Bump into `isBuiltin` when trying to define something similar for the language server.
Quick question in the meantime, where can I find [prelude](https://github.com/diku-dk/futhark/tree/master/prelude) in the filesystem after installing futhark?

extract isBuiltin to Language.Futhark.Prop

---

CHANGELOG.md
docs/c-api.rst
rts/c/cache.h
rts/c/cuda.h
rts/c/opencl.h
src/Futhark/CodeGen/Backends/CCUDA/Boilerplate.hs
src/Futhark/CodeGen/Backends/COpenCL/Boilerplate.hs
src/Futhark/CodeGen/Backends/GenericC.hs
src/Futhark/CodeGen/Backends/GenericC/CLI.hs
src/Futhark/CodeGen/Backends/GenericC/Server.hs
src/Futhark/CodeGen/Backends/MulticoreC.hs
src/Futhark/CodeGen/Backends/SequentialC/Boilerplate.hs
src/Futhark/CodeGen/RTS/C.hs

Implement caching mechanism for OpenCL and CUDA.

---

src/Futhark/Compiler/Program.hs

Files managed by VFS are not identified as changed.
Repro:
1. Open a well-written (without errors) futhark file
2. Start deleting things so that the program is wrong (without saving the file)
3. No diagnostic is published
Also, do we want to rename this to `lfCheckedTime` or something?
https://github.com/diku-dk/futhark/blob/5f69a46d87b81ab963a2cb532a05c924f42c72be/src/Futhark/Compiler/Program.hs#L64

Always re-check files managed by VFS

---

CHANGELOG.md
docs/man/futhark-test.rst
src/Futhark/CLI/Test.hs

futhark test: only interpret with -i.

---

CHANGELOG.md
cabal.project
docs/man/futhark-literate.rst
futhark.cabal
nix/futhark-server.nix
src/Futhark/CLI/Literate.hs
tests_adhoc/literate_trace/test.sh
tests_adhoc/literate_trace/trace.fut

futhark literate: -v option now prints trace output.

---

CHANGELOG.md
rts/c/server.h
src/Futhark/CodeGen/Backends/CCUDA.hs
src/Futhark/CodeGen/Backends/COpenCL.hs
src/Futhark/CodeGen/Backends/GenericC.hs
src/Futhark/CodeGen/ImpGen/GPU/ToOpenCL.hs

Make more host-device copies asynchronous.

---

src/Futhark/CLI/Main.hs

Small fix to correct the description of the `tokens` command

Update description for tokens command

---

src/Futhark/Optimise/ArrayShortCircuiting.hs
src/Futhark/Optimise/ArrayShortCircuiting/ArrayCoalescing.hs
src/Futhark/Optimise/ArrayShortCircuiting/LastUse.hs

This is simply necessary in order for the information to be correct, as implemented in the other pass to fix #1755.  It does not have any effect on short-circuiting however, as we do not apply it in constants.  (But we might one day, soon.)
The motivation for this is perhaps switching over to Futhark.Optimise.ArrayShortCircuiting.LastUse as the sole "LastUse" computation.

Make Futhark.Optimise.ArrayShortCircuiting.LastUse program-wide.

---

src/Futhark/Optimise/ArrayShortCircuiting/MemRefAggreg.hs
tests/memory-block-merging/coalescing/issue-1789.fut
tests/memory-block-merging/coalescing/lud/lud.fut
tests/memory-block-merging/coalescing/lud/lud_internal1-16.fut
tests/memory-block-merging/coalescing/lud/lud_internal1.fut
tests/memory-block-merging/coalescing/lud/lud_internal2.fut
tests/memory-block-merging/coalescing/lud/lud_internal3.fut
tests/memory-block-merging/coalescing/lud/lud_internal6.fut

MemRefAggreg: Include current destination uses when checking overlap

---

CHANGELOG.md
src/Futhark/IR/SOACS/Simplify.hs
src/Futhark/Optimise/Simplify/Rules.hs
src/Futhark/Optimise/Simplify/Rules/Index.hs
tests/issue1808.fut

The certificate design is actually pretty good, but we have to be careful about maintaining them, and we are... not always, really.
Fixes #1808.

Fix mismanagement of certs in simplification rules.

---

docs/man/futhark-literate.rst
src/Futhark/CLI/Literate.hs
tests_literate/expected/audio.md

Also, let you change the sampling frequency of the input.

futhark-literate: Add support for more input formats, output codecs

---

CHANGELOG.md
rts/c/context.h
rts/c/context_prototypes.h
rts/c/cuda.h
rts/c/free_list.h
rts/c/opencl.h
src/Futhark/CodeGen/Backends/CCUDA/Boilerplate.hs
src/Futhark/CodeGen/Backends/COpenCL/Boilerplate.hs
src/Futhark/CodeGen/Backends/GenericC.hs
src/Futhark/CodeGen/Backends/GenericC/Monad.hs
src/Futhark/CodeGen/Backends/MulticoreC.hs
src/Futhark/CodeGen/Backends/SequentialC/Boilerplate.hs
src/Futhark/CodeGen/ImpGen.hs
src/Futhark/CodeGen/ImpGen/Multicore.hs

Starting with #1799, but I will also address #1768.

Improvements to the multicore backend

---

CHANGELOG.md
docs/man/futhark-pkg.rst
docs/package-management.rst
futhark.cabal
src/Futhark/CLI/Pkg.hs
src/Futhark/Pkg/Info.hs
src/Futhark/Pkg/Solve.hs
src/Futhark/Util/Log.hs

futhark pkg: use 'git' directly.

---

CHANGELOG.md
docs/man/futhark.rst
futhark.cabal
src/Futhark/CLI/Eval.hs
src/Futhark/CLI/Main.hs
tests_adhoc/eval/test.fut
tests_adhoc/eval/test.sh

Add futhark eval command

---

.github/workflows/main.yml

If this does not fix Windows, then I will remove it (again).

Switch to GHC 9.4 in Cabal CI.

---

src/Futhark/IR/Syntax/Core.hs
src/Language/Futhark/Syntax.hs

Adresses https://github.com/haskell/core-libraries-committee/issues/93

Add Foldable and Traversable instances

---

futhark.cabal
src/Futhark/IR/Mem/IxFun.hs
src/Futhark/IR/Mem/LMAD.hs

The idea is that the LMAD module is fairly principled and generally useful, and IxFun is just whatever we put together to serve as index functions.

Put LMADs in their own module.

---

src/Futhark/CodeGen/Backends/CCUDA.hs
src/Futhark/CodeGen/Backends/COpenCL.hs

This is partially to make the generated code look nicer, but it also makes it feasible to eventually run single kernels in isolation, for autotuning purposes.

Put kernel invocations in separate function.

---

rts/c/backends/cuda.h
rts/c/backends/opencl.h
rts/c/util.h
src/Futhark/CodeGen/Backends/CCUDA/Boilerplate.hs
src/Futhark/CodeGen/Backends/COpenCL/Boilerplate.hs

Previously we had fixed fields in the 'program' struct, but this was quite inflexible in some cases.

Track cost centres dynamically.

---

prelude/array.fut

Correction of work complexity for tabulate_2d and tabulate_3d.

Copy-paste mistake

---

src/Futhark/Pass/ExtractKernels/DistributeNests.hs
tests/distribution/map-duplicate.fut
tests/distribution/map-replicate.fut
tests/memory-block-merging/coalescing/chain/blk-chain4.fut

This reminds me that I'd rather just finish the proper flattening pass.

Fixing a few edge cases in distribution

---

HACKING.md

Code generation flags have changed

---

rts/python/memory.py
rts/python/scalar.py
rts/python/values.py
src/Futhark/CodeGen/Backends/GenericPython.hs
src/Futhark/CodeGen/Backends/GenericPython/AST.hs
src/Futhark/CodeGen/Backends/PyOpenCL.hs
src/Futhark/CodeGen/Backends/SequentialPython.hs

This is easier to understand and maintain.

Python backend: use more numpy and less ctypes.

---

docs/man/futhark-profile.rst
src/Futhark/CLI/Profile.hs

Minor fixes related to multiple entry points/programs that I noticed while trying out the new profiling CLI.

futhark profile fixup

---

src/Futhark/CodeGen/ImpGen/GPU/Base.hs
src/Futhark/CodeGen/ImpGen/Multicore/SegMap.hs
src/Futhark/IR/Parse.hs
src/Futhark/IR/Prop/Types.hs
src/Futhark/IR/SegOp.hs
src/Futhark/IR/TypeCheck.hs
src/Futhark/Optimise/ArrayShortCircuiting/ArrayCoalescing.hs
src/Futhark/Optimise/BlkRegTiling.hs
src/Futhark/Optimise/InPlaceLowering/LowerIntoStm.hs
src/Futhark/Optimise/TileLoops/Shared.hs
src/Futhark/Pass/ExtractKernels.hs
src/Futhark/Pass/ExtractKernels/DistributeNests.hs
src/Futhark/Pass/ExtractKernels/Intragroup.hs
src/Futhark/Pass/ExtractMulticore.hs

In particular, WriteReturns now supports (and requires) arbitrary slices.

Make WriteReturns simpler, yet more flexible.

---

futhark.cabal

So that they are available from Hackage.

Add CHANGELOG.md and README.md to extra-doc-files

---

src/Futhark/Optimise/DoubleBuffer.hs

Hopefully we can get away with just one algorithm now.

Eliminate double buffering by copy.

---

.github/workflows/main.yml

Fix windows CI actions that were previously disabled due to compilation failures.

Re-enable windows CI actions.

---

.github/workflows/main.yml

enable windows binary to release deploy-nightly.

enable windows binary to release deploy-nightly.

---

CHANGELOG.md
futhark.cabal
src/Language/Futhark/Semantic.hs
unittests/Language/Futhark/SemanticTests.hs
unittests/futhark_tests.hs

Fix handling of .. in import paths.

---

cabal.project
docs/c-api.rst
docs/manifest.schema.json
futhark.cabal
nix/futhark-manifest.nix
src/Futhark/CodeGen/Backends/GenericC/CLI.hs
src/Futhark/CodeGen/Backends/GenericC/EntryPoints.hs
src/Futhark/CodeGen/Backends/GenericC/Monad.hs
src/Futhark/CodeGen/Backends/GenericC/Server.hs
src/Futhark/CodeGen/Backends/GenericC/Types.hs
src/Futhark/CodeGen/Backends/SimpleRep.hs
src/Futhark/CodeGen/ImpGen.hs
src/Futhark/IR/Parse.hs
src/Futhark/IR/Pretty.hs
src/Futhark/IR/Syntax/Core.hs
src/Futhark/IR/TypeCheck.hs
src/Futhark/Internalise/Entry.hs
tests_lib/c/index.fut
tests_lib/c/opaque_array.fut
tests_lib/c/record_array.fut
tests_lib/c/test_index.c
tests_lib/c/test_opaque_array.c
tests_lib/c/test_record_array.c
tests_lib/c/test_restore.c

Add support for indexing/zipping/projecting opaque arrays.

---

CHANGELOG.md
src/Futhark/Internalise/Entry.hs
tests_lib/c/opaque_array.fut
tests_lib/c/test_opaque_array.c

Track entry point array element type expressions.

---

src/Futhark/Analysis/HORep/SOAC.hs

I think these were necessary once, but no more.

Get rid of ReshapeInner/ReshapeOuter.

---

CHANGELOG.md
src/Language/Futhark/Parser/Parser.y
src/Language/Futhark/TypeChecker.hs
src/Language/Futhark/TypeChecker/Modules.hs
tests/modules/ascription-sizelifted3.fut
tests/modules/liftedness2.fut
tests/modules/liftedness3.fut

I am somewhat uneasy about this one, but I think it is necessary for some fancy module-level programming.

Allow type refinements to be lifted.

---

CHANGELOG.md
src/Futhark/CodeGen/ImpGen/GPU/Base.hs
src/Futhark/CodeGen/ImpGen/GPU/ToOpenCL.hs
tests/issue2294.fut

This fixes the code generator, but these accumulator updates are in any case not necessary. It would be nice to have an optimisation earlier on that identifies and removes them.

Fix #2294.

---

CHANGELOG.md
src/Futhark/CLI/Literate.hs
src/Futhark/Test.hs
src/Futhark/Util.hs

Implement cachedir specification.
