docs/language-reference.rst
futhark.cabal
src/Futhark/Actions.hs
src/Futhark/CodeGen/Backends/COpenCL.hs
src/Futhark/CodeGen/Backends/COpenCL/Boilerplate.hs
src/Futhark/CodeGen/Backends/GenericC.hs
src/Futhark/CodeGen/Backends/GenericPython.hs
src/Futhark/CodeGen/Backends/SequentialC.hs
src/Futhark/CodeGen/Backends/SequentialPython.hs
src/Futhark/CodeGen/ImpCode.hs
src/Futhark/CodeGen/ImpCode/Kernels.hs
src/Futhark/CodeGen/ImpCode/OpenCL.hs
src/Futhark/CodeGen/ImpCode/Sequential.hs
src/Futhark/CodeGen/ImpGen.hs
src/Futhark/CodeGen/ImpGen/Kernels.hs
src/Futhark/CodeGen/ImpGen/Kernels/ToOpenCL.hs
src/Futhark/CodeGen/ImpGen/OpenCL.hs
src/Futhark/CodeGen/ImpGen/Sequential.hs
src/Futhark/CodeGen/SetDefaultSpace.hs

The biggest difference is that I have created specialised modules for each invariant of the imperative code, including a new one that contains OpenCL (`Futhark.CodeGen.ImpCode.OpenCL`).  This is the one you will use when you get to OpenCL code generation (and also the main motivation for this merge).
I modified your Python code generator to import `Futhark.CodeGen.ImpCode.Sequential`, because right now it's not really a generic code generator.  Once you get further, we will move back to importing the generic `Futhark.CodeGen.ImpCode`, but for now, let's pretend imperative code is our only care in the world.

Merge with master.

---

data/tests/vasicek/iobound-mc2.fut
src/Language/Futhark/Parser/Lexer.x
src/Language/Futhark/Parser/Parser.y
src/Language/Futhark/Parser/Tokens.hs

Reverts HIPERFIT/futhark#129
That is kind of useless without constants being usable without parentheses..
I wouldn't have merged that!

Revert "const, closes #123"

---

docs/windows-installation.rst

This is kind of essential, but I was using the tools from some other library that I was not even aware about until I accidentally removed them from `PATH`. They also randomly get corrupted and require a reboot. Thankfully, Git for Windows has a bunch of higher quality ones with it. I needed to clarify this.

Added information on how to install the Linux command line tools to the documentation

---

data/tests/distribution/distribution3.fut
data/tests/distribution/distribution5.fut
data/tests/streamRed_interchange.fut
src/Futhark/CodeGen/ImpGen/Kernels.hs
src/Futhark/Pass/ExpandAllocations.hs
src/Futhark/Pass/ExplicitAllocations.hs
src/Futhark/Pass/ExtractKernels/BlockedKernel.hs
src/Futhark/Pass/KernelBabysitting.hs
src/Futhark/Representation/Kernels/Kernel.hs
src/Futhark/Representation/Kernels/Simplify.hs

Fixes #176 .
There is still room for improvement.  Thrust uses a technique where every thread processes several elements, not just one.  We could do that as well, at the cost of using more local memory.

Faster scans

---

futhark.cabal
src/Futhark/Version.hs
stack-lts-1.15.yaml

Output of `futhark --version` will now be like the following. I think the format for the timestamp of the commit is horrible, but I do think it is important to have, as it tells you how recent a version was used which is usually what you want to know for non debugging purposes. 
```
Futhark 0.1
git: 8791fd4 (Wed Jan 11 18:26:23 2017 +0100)
(C) HIPERFIT research centre
Department of Computer Science, University of Copenhagen (DIKU)
```
If the branch is not "master", the branchname will be inserted before the hash, and if any files have been modified this will be displayed at the end of the line
Due to the way the `gitrev` package works (using TemplateHaskell),
`Futhark.Version` and `Futhark.Util.Options` will be recompiled on *every*
compilation. This kinda sucks, and is why I didn't just …

Add git info to --version

---

src/Futhark/Pass/ExtractKernels.hs

Just wanted your approval before commiting this to master. Seems like things
could break from this change, but I ran both the testsuite and the benchmarks,
and nothing showed up.
I ran the testsuite with `$ futhark-test --only-compile --compiler='futhark-opencl' tests`
this gives the same errors both with and without this change in the following files
```
tests/array14-running-example.fut
tests/distribution/distribution7.fut
tests/flattening/IntmRes4.fut
tests/distribution/irregular1.fut
tests/issue194.fut
tests/shapes/lambda-return.fut
tests/soacs/map11.fut
tests/soacs/scan2.fut
tests/vasicek/iobound-mc2.fut
```

Don't manifest arrays in isSegmentedOp when extracting kernels

---

tools/futhark-mode.el

Using cl-lib is preferable to using cl.el for emacs lisp coding convention. (cl-lib.el was bundled since Emacs 24.3. So emacs 24.3 or higher version users need not to install it).

Use cl-lib instead of cl.el

---

rts/python/reader.py
src/Futhark/CodeGen/Backends/GenericPython.hs
src/Futhark/CodeGen/Backends/GenericPython/Definitions.hs
src/Futhark/CodeGen/Backends/PyOpenCL.hs
src/Futhark/CodeGen/Backends/SequentialPython.hs

`read_double_signed` was used to read `f64`, but reading `f32` did not use this function, but just `read_double`.
Wanted to make sure there was no reason for handling negative numbers twice for `f64` and not doing so for `f32`, so that is why I made the pull request.

Clean up python RTS reader

---

tools/futcolor

As a human, I find it easier to read Futhark output with (generated) variable names in colorz.
Works well in 256-colors terminals, with all kind of futhark outputs (C/py OpenCL, futhark IL, ...)

[add] fucolor utility: colorize vars in futhark output

---

rts/python/scalar.py
tests/size-from-division.fut

Previously, division of two integers could result in a float.

Fix integer division in the Python backend.

---

futlib/array.fut
futlib/math.fut
futlib/prelude.fut
package.yaml
src/Futhark/Compiler.hs
src/Futhark/Compiler/TH.hs
src/Futhark/Doc/Generator.hs
src/Futhark/FreshNames.hs
src/Futhark/Optimise/Simplifier/Rules.hs
src/Language/Futhark/Attributes.hs
src/Language/Futhark/Core.hs
src/Language/Futhark/Futlib.hs
src/Language/Futhark/Futlib/Prelude.hs
src/Language/Futhark/TH.hs
src/Language/Futhark/TypeChecker.hs
src/Language/Futhark/TypeChecker/Monad.hs
src/futhark-c.hs
src/futhark-doc.hs
src/futhark-opencl.hs
src/futhark-py.hs
src/futhark-pyopencl.hs
src/futhark-test.hs
src/futhark.hs
src/futharki.hs

Any Futhark program now implicitly opens "/futlib/prelude".
Slowdown is avoided by using Template Haskell to parse and type-check
the prelude at (Haskell) compile time.
Not sure it's worth it.

Add implicit prelude to Futhark programs.

---

src/Futhark/CodeGen/Backends/COpenCL.hs
src/Futhark/CodeGen/Backends/GenericC.hs
src/Futhark/CodeGen/Backends/GenericPython.hs
src/Futhark/CodeGen/Backends/PyOpenCL.hs
src/Futhark/CodeGen/Backends/SequentialC.hs
src/Futhark/CodeGen/Backends/SequentialPython.hs

In the generated code, C or Python: If performing a warmup run or
running more than one time, first copy any parameter memory blocks
before each run.  This ensures that programs that write to unique
input arrays do not cause a problem in future runs.
The copying occurs before the timing begins.
Currently (when in benchmarking mode) the compiler copies every
parameter memory block.  It would be more efficient to copy only those
associated with a unique array.  That would seemingly mean some
additions to the ImpCode representation.
Related to issue #388.

Copy entry function memory blocks when benchmarking.

---

docs/language-reference.rst
src/Language/Futhark/Parser/Lexer.x
src/Language/Futhark/Parser/Parser.y
tests/hexfloats.fut

See: https://github.com/diku-dk/futhark/issues/382
This does not include changes for Python and C readers.

Support hexadecimal float literals in lexer and parser

---

src/Futhark/Internalise/Defunctionalise.hs

Type variables are eliminated by the monomorphizer, so this is not needed anymore and it was mostly a temporary solution anyway. The comment is confusing and no longer applies.

Remove old cases for type variables from defunctionalizer.

---

futlib/segmented.fut
tests/futlib_tests/segmented.fut

The `accelerate/pagerank` benchmark needs to be modified as well.

Use higher-order functions instead of modules for segmented_scan.

---

README.md

The label newbie-friendly doesn't seem to exist anymore and I'm assuming "good first issue" has taken it's place.

Update link to beginner issues in README.md

---

package.yaml
src/Futhark/Test.hs

A first attempt at implementing #416 . I wasn't sure if I should add any tests for the issue (esp. since futhark-benchmarks is a separate repo) so I've left it as-is. 
The change simply decompresses any input files that end in ".gz".

Support for gzipped files for futhark-bench/futhark-test  

---

src/futhark-test.hs

At the moment, the case reporting is super rudimentary and only appears at the end of output. I also started working on #209 in parallel so I figured it'd be best to not embellish too much here and leave improving the output for that issue.
I also refactored `runTests` a good bit by adding a `TestStatus` record. @Athas, if you're not a fan of these changes, I can also simply tack on a "cases run" argument to `getResults`.
Finally, I thought it would also potentially be nice to report the number of cases failed/passed, but this would be more involved to add. It's also (somewhat) at odds with how `futhark-test` currently reports errors; namely, it only reports a single error per file (even if there are multiple).

Adds case reporting to futhark-test. (#421)

---

futlib/soacs.fut
src/Futhark/Analysis/HORepresentation/SOAC.hs
src/Futhark/Internalise.hs
src/Futhark/Internalise/Monomorphise.hs
src/Futhark/Optimise/Fusion.hs
src/Futhark/Optimise/Fusion/LoopKernel.hs
src/Language/Futhark/Attributes.hs
src/Language/Futhark/Syntax.hs
tests/genred/array.fut
tests/genred/equiv.fut
tests/genred/simple.fut
tests/genred/tuple.fut

This implements simple producer-consumer map-genreduce fusion.
It also slightly changes the source language `gen_reduce` to no longer accept a bucket function, but a bucket array.

Genreduce fusion

---

src/Futhark/CodeGen/ImpGen/Kernels.hs
src/Futhark/CodeGen/ImpGen/Kernels/ToOpenCL.hs

This allows utilizing a handful of atomic implementations when
generating code for GenReduce.

Add recognition of binary operators

---

src/Futhark/CodeGen/ImpGen/Kernels.hs
src/Futhark/Pass/ExplicitAllocations.hs
src/Futhark/Pass/ExtractKernels.hs
src/Futhark/Pass/ExtractKernels/BlockedKernel.hs
src/Futhark/Pass/ExtractKernels/Segmented.hs
src/Futhark/Representation/Kernels/KernelExp.hs

The previous implementation would let all threads write to the same histogram in global memory. This solution lets threads cooperate on subhistograms (still in global memory) before summing them all up into the final histogram.

Implement cooperation level for GenReduce

---

package.yaml
src/Futhark/Test.hs
src/Futhark/Test/Values.hs
src/Futhark/Util/Table.hs
src/futhark-bench.hs
src/futhark-test.hs

Changes:
- Adds error accumulation. `futhark-test` will now report all errors for a program, with some limitations (which can be easily changed as desired): Structure tests, warning tests, compile tests, compiled tests, and interpreted tests do not mutually accumulate. For example, if there is an error when running a compiled test, futhark-test will not run any interpreted tests for that program. This can be modified by placing an `accErrors_` call in the relevant place but I thought this was the most reasonable implementation.
- Adds (basic) table building and uses it to format the output of `futhark-test` more clearly.
- Adds a (tiny) bit of color to the output of `futhark-test` :) 
- Because `futhark-test` now allows for multiple failures when testing a program, `<test>.fut.actual` and …

Adds error accumulation to futhark-test, addresses issues #630/#421, improves futhark-test output.

---

src/Language/Futhark/Interpreter.hs

Attempt to fix https://github.com/diku-dk/futhark/issues/637
The pretty printer after this commit:
```
replicate 10 (replicate 10 0)
[[0i32, 0i32, 0i32, 0i32, 0i32, 0i32, 0i32, 0i32, 0i32, 0i32]
, [0i32, 0i32, 0i32, 0i32, 0i32, 0i32, 0i32, 0i32, 0i32, 0i32]
, [0i32, 0i32, 0i32, 0i32, 0i32, 0i32, 0i32, 0i32, 0i32, 0i32]
, [0i32, 0i32, 0i32, 0i32, 0i32, 0i32, 0i32, 0i32, 0i32, 0i32]
, [0i32, 0i32, 0i32, 0i32, 0i32, 0i32, 0i32, 0i32, 0i32, 0i32]
, [0i32, 0i32, 0i32, 0i32, 0i32, 0i32, 0i32, 0i32, 0i32, 0i32]
, [0i32, 0i32, 0i32, 0i32, 0i32, 0i32, 0i32, 0i32, 0i32, 0i32]
, [0i32, 0i32, 0i32, 0i32, 0i32, 0i32, 0i32, 0i32, 0i32, 0i32]
, [0i32, 0i32, 0i32, 0i32, 0i32, 0i32, 0i32, 0i32, 0i32, 0i32]
, [0i32, 0i32, 0i32, 0i32, 0i32, 0i32, 0i32, 0i32, 0i32, 0i32]
]
```
And for cases when the total …

[WIP] Improve the pretty printer formatting for higher dimensional arrays

---

examples/rosettacode/life.fut
futlib/math.fut
rts/csharp/scalar.cs
rts/python/scalar.py
src/Futhark/CodeGen/Backends/SimpleRepresentation.hs
src/Futhark/Representation/Primitive.hs

This saves a lot of (tiny) branches in some programs.

Add itob/btoi intrinsics for bool/integer conversions.

---

futlib/array.fut

Fix to the typo in tabulate_3d, which caused the function to fail. Array now has correct dimensions.

Fixed tabulate_3d.

---

src/Futhark/CodeGen/ImpGen/Kernels/ToOpenCL.hs
src/Futhark/CodeGen/OpenCL/Kernels.hs

For the TransposeNormal transposition type:
Change group size to 32x8 and make threads transpose 4 elements each.
This means that each group now transposes a tile of size 32x32.

Transpose 4 elements per thread in TransposeNormal

---

src/Futhark/CodeGen/ImpGen/Kernels.hs
src/Futhark/CodeGen/ImpGen/Kernels/Base.hs
src/Futhark/CodeGen/ImpGen/Kernels/SegGenRed.hs
src/Futhark/Pass/ExpandAllocations.hs
src/Futhark/Pass/ExplicitAllocations.hs
src/Futhark/Pass/ExtractKernels.hs
src/Futhark/Pass/ExtractKernels/BlockedKernel.hs
src/Futhark/Representation/ExplicitMemory.hs
src/Futhark/Representation/Kernels/Kernel.hs
src/Futhark/Representation/Kernels/Simplify.hs

This is to permit more specialised implementations by @nqpz.
For stupid technical reasons, the lock array we create for advanced
operators is currently much too small.  That will have to be fixed.

Turn generalised reductions into their own kernel construct.

---

docs/versus-other-languages.rst

Here are some wording suggestions and typo fixes for Chapter 6 of the language reference.

Chapter 6 (versus other languages) wording

---

src/Futhark/CodeGen/Backends/GenericC.hs

An attempt to add header guards to generated C headers, resolving #718. @athas, may I ask your advice on where to draw the filename from? I thought I could use one of the generated function filepaths but this ended up evaluating to GenericC.hs instead of the C file like I intended. 
Thank you very much for your time. 
Max

Header guards

---

futlib/math.fut

'even' is not used or even available (not part of the module type).

Remove the 'even' function in the f32 and f64 modules.

---

src/Futhark/CodeGen/Backends/GenericC.hs

Work towards proper header guards (#747). 
The header guard name is hardcoded right now, coming full circle from my `pragma once` patch :sweat_smile:. 
I started plumbing the `.fut` name from the backends outwards and felt like I was vandalizing all the function signatures for a small benefit (at one point having to tweak C# backend code for a C-related change). This is probably mostly an inexperience thing.
The change seems more justifiable to support more relevant public names, but perhaps it's better to defer that decision.

Fix #pragma once compiler warnings 

---

src/Futhark/CodeGen/ImpGen/Kernels/Base.hs

If the number of elements to process is exactly equal to the number of threads
available, we don't need to add a for-loop and can instead execute the code
within directly.

Remove unnecessary for-loop in kernelLoop

---

docs/man/futhark-bench.rst
docs/man/futhark-opencl.rst

This is an attempt at addressing my questions in #827. 
The answers have been inferred by inspecting this patch to the rodinia benchmarks created by @athas: https://github.com/diku-dk/futhark-pldi17/blob/master/rodinia_3.1-some-instrumentation.patch. By inspecting the changes to nearestNeighbor.cpp, it looks like writing to buffers is not included, but reading from buffers is.

Add section about what `futhark bench` measures

---

src/Futhark/Representation/ExplicitMemory/IndexFunction.hs

The documentation mentions a general permutation parameter, as well as
dimension-wise unit-strides, none of which can be found in the current code. I
also took the liberty of rewriting the paragraph describing how LMADs together
with a shape and a contiguousness bit make up an index function.

Update IndexFunction documentation

---

src/Futhark/Analysis/PrimExp.hs
src/Futhark/Analysis/PrimExp/Convert.hs
src/Futhark/Analysis/PrimExp/Generalize.hs
src/Futhark/CodeGen/ImpGen.hs
src/Futhark/Pass/ExplicitAllocations.hs
src/Futhark/Representation/AST/Syntax/Core.hs
src/Futhark/Representation/ExplicitMemory.hs
src/Futhark/Representation/ExplicitMemory/IndexFunction.hs
tests/memory-block-merging/misc/ixfun-antiunif-1.fut
tests/memory-block-merging/misc/ixfun-antiunif-2.fut
tests/memory-block-merging/misc/ixfun-loop.fut

The purpose of this commit is to decrease copies in if-then-else branches.
Before, if two branches of an if-then-else returned arrays with different index
functions (LMADs), the compiler would normalize the arrays in one or both of the
branches, which could result in unnecessary copying.
With this commit, the compiler will try to generalize the index functions and
return the existentials in addition to the array itself. Consider the following
expression:
```futhark
if (arr[0] < 0.0)
then arr[2+n/2:n]
else arr[2+n/4:n]
```
Before, the results would be copied into fresh arrays in both branches, but
really, we could return the same array as before in addition to the computed
offsets to the index function. This way, we can avoid some unnecessary copies.
Along the way, we've had to relax the …

Index function generalization/antiunification across if-then-else

---

docs/language-reference.rst
src/Futhark/CLI/REPL.hs
src/Futhark/Internalise/Defunctionalise.hs
src/Futhark/Internalise/Monomorphise.hs
src/Language/Futhark/Attributes.hs
src/Language/Futhark/Pretty.hs
src/Language/Futhark/TypeChecker.hs
src/Language/Futhark/TypeChecker/Modules.hs
src/Language/Futhark/TypeChecker/Terms.hs
src/Language/Futhark/TypeChecker/Types.hs
tests/operator/section3.fut
tests/operator/section4.fut
tests/shapes/concatmap.fut
tests/shapes/emptydim3.fut
tests/shapes/error10.fut
tests/shapes/error11.fut
tests/shapes/error8.fut
tests/shapes/flatmap.fut
tests/shapes/funshape0.fut
tests/shapes/funshape1.fut
tests/shapes/funshape2.fut
tests/shapes/funshape3.fut
tests/shapes/modules1.fut
tests/shapes/negative-position-shape0.fut
tests/shapes/negative-position-shape1.fut
tests/shapes/negative-position-shape3.fut
tests/shapes/negative-position-shape4.fut
tests/shapes/size-inference6.fut
tests/types/alias-error5.fut

A size parameter need no longer be used in an actual array.  But if
you don't, then there are some other restrictions on how the overall
binding can be used.  Basically: the size parameter must be inferable
at the point of instantiation.
Now @kfl can get his concatmap and flatmap working.

Loosen the restrictions on size parameters.

---

src/Futhark/Representation/ExplicitMemory.hs

We no longer require the shape of the index function and the shape of the
MemArray to match.

Remove unnecessary shape check

---

CHANGELOG.md
src/Futhark/CodeGen/ImpGen/Kernels/Base.hs
src/Futhark/CodeGen/ImpGen/Kernels/SegRed.hs
src/Futhark/CodeGen/ImpGen/Kernels/SegScan.hs
tests/soacs/scan2.fut

The code generator makes heavy assumptions on the memory layout
provided by the allocator.

Support arbitrary scan operators that take arrays.

---

rts/c/scheduler.h
src/Futhark/CodeGen/Backends/GenericC.hs
src/Futhark/CodeGen/Backends/MulticoreC.hs

Also change the scheduler to not know about `futhark_context`.
This is much better than hardcoding multicore stuff in GenericC.hs.  The OpenCL backend can work without having anything OpenCL-specific in GenericC.hs, and I would be surprised if the same is not the case for the multicore backend.

Initialise multicore stuff in new_context.

---

src/Futhark/Passes.hs

With this change, I get a 2.3x speedup on LocVolCalib with 4 threads versus sequential execution.

Use a slightly more multicore-focused compiler pipeline.

---

rts/c/jobqueue.h
rts/c/scheduler.h
src/Futhark/CLI/Multicore.hs
src/Futhark/CodeGen/Backends/MulticoreC.hs

This also pushes the information about thread count into the job queue
struct.  I think the notion of "scheduler" and "job queue" should be
unified, and a dedicated scheduler struct used (like the OpenCL
backend has an opencl struct).

Dynamically detect the number of threads to use.

---

docs/man/futhark-bench.rst
src/Futhark/Bench.hs
src/Futhark/CLI/Autotune.hs
src/Futhark/CLI/Bench.hs

Not used for much at the moment, mainly to get the command line arguments used in each benchmark run.

Add verbose flag to `futhark bench`

---

prelude/soacs.fut

The docs referred to a neutral element for "`op`", but this particular function (`reduce_by_index`) has the relevant parameter named `f`. This PR fixes the typo.

Fix typo in prelude/soacs docs

---

src/Futhark/CLI/Test.hs
src/Futhark/Util/Pretty.hs
src/Futhark/Util/Table.hs
src/Language/Futhark/TypeChecker/Monad.hs

Print the "Error" part of a TypeError in red with the error message right after it. 
(c.f. #912)
For [duplicate parameters](https://github.com/diku-dk/futhark/blob/master/tests/errors/duplicate-params.fut), the error message is: 
```text
Error: Name "x" also bound at .\tests\errors\duplicate-params.fut:6:11-11.                                
at: .\tests\errors\duplicate-params.fut:6:20-20                          
```
(paths are weird because I'm on windows, double "at" is a little clunky)
instead of 
```text
Error at .\tests\errors\duplicate-params.fut:6:20-20:
Name x also bound at .\tests\errors\duplicate-params.fut:6:11-11
If you find this error message confusing, uninformative, or wrong, please open an issue at https://github.com/diku-dk/futhark/issues.
```

Print TypeError "Error" in red

---

src/Futhark/Bench.hs
src/Futhark/CLI/Autotune.hs

The purpose of this PR is to improve the autotuner by taking into account programs with changing levels of parallelism. Previous to this commit, if a program had different levels of parallelism, we call them `ePar`, the autotuner would choose the first one it encountered. In the LUD benchmark, that would always be the highest `ePar`, since the level of parallelism is decreasing. But how do we know that this is the best ePar to compare against?
With these changes, the autotuner will be equipped to handle such cases. It employs a binary search combined with continual refinement of the search space to efficiently find the threshold value that guarantees optimal performance across all test datasets.
The changes build upon the following realization, which also motivated not using ranges for …

 Implement binary searching in Autotuner, take 2

---

.travis.yml
azure-pipelines.yml
libtests/README.md
libtests/c/Makefile
libtests/c/README.md
libtests/c/a.fut
libtests/c/b.fut
libtests/c/test_a.c
libtests/c/test_b.c

Only for the C backend for now.  We can extend this as needed in the
future to prevent regressions.
Closes #900.

Get started on some library backend tests.

---

shell.nix

This should make it easier to drop into a development environment using `nix-shell`.

Add opencl-headers, ocl-icd and hlint to shell.nix

---

src/Futhark/CLI/Autotune.hs

When there are only two ePars left to tune on, we erroneously only tried the
second one. This code makes sure that we try both values of ePar.

Fix binary tune case with only two ePars left

---

rts/c/opencl.h
rts/csharp/opencl.cs
src/Futhark/CodeGen/Backends/CCUDA.hs
src/Futhark/CodeGen/Backends/COpenCL/Boilerplate.hs
src/Futhark/CodeGen/Backends/CSOpenCL.hs
src/Futhark/CodeGen/Backends/CSOpenCL/Boilerplate.hs
src/Futhark/CodeGen/Backends/PyOpenCL.hs
src/Futhark/CodeGen/Backends/PyOpenCL/Boilerplate.hs
src/Futhark/CodeGen/ImpGen.hs
src/Futhark/CodeGen/ImpGen/Kernels/Base.hs
src/Futhark/CodeGen/OpenCL/Heuristics.hs
src/Futhark/Optimise/BlkRegTiling.hs
src/Futhark/Representation/Kernels/Sizes.hs

Also introduces a new "register tile" size.
Does not generate working code, but it's unclear whether the problem
is in the code generation or the register tiling pass itself.

Preliminary code generation for register tiling.

---

futhark.cabal
src/Futhark/CLI/Dev.hs
src/Futhark/Pass/ExpandAllocations.hs
src/Futhark/Pass/ExtractKernels.hs
src/Futhark/Pass/ExtractKernels/BlockedKernel.hs
src/Futhark/Pass/ExtractKernels/DistributeNests.hs
src/Futhark/Pass/ExtractKernels/Distribution.hs
src/Futhark/Pass/ExtractKernels/Intragroup.hs
src/Futhark/Pass/ExtractKernels/StreamKernel.hs
src/Futhark/Pass/ExtractKernels/ToKernels.hs
src/Futhark/Pass/ExtractMulticore.hs
src/Futhark/Representation/Kernels.hs
src/Futhark/Representation/Kernels/Simplify.hs
src/Futhark/Representation/MC.hs
src/Futhark/Representation/SegOp.hs

This PR re-introduces a significant degree of flattening to the multicore backend.  In practice, nested SegOps will only occur in cases of irregular parallelism.
We will probably need to experiment with the right way to flatten for the multicore backend.  It is definitely worth flattening simple `map`s, and probably also doing `loop` interchange, but it may not be worth it to produce e.g. actual multi-dimensional `SegRed`s in most cases.

Apply moderate flattening for multicore backend

---

src/Futhark/CodeGen/ImpGen.hs
src/Futhark/CodeGen/ImpGen/Kernels.hs
src/Futhark/CodeGen/ImpGen/Kernels/Base.hs
src/Futhark/CodeGen/ImpGen/Kernels/SegHist.hs
src/Futhark/CodeGen/ImpGen/Kernels/SegRed.hs
src/Futhark/CodeGen/ImpGen/Kernels/SegScan.hs
src/Futhark/Pass/ExpandAllocations.hs
src/Futhark/Pass/ExplicitAllocations/Kernels.hs
src/Futhark/Pass/ExtractKernels.hs
src/Futhark/Pass/ExtractKernels/BlockedKernel.hs
src/Futhark/Pass/ExtractKernels/DistributeNests.hs
src/Futhark/Pass/ExtractKernels/Intragroup.hs
src/Futhark/Pass/ExtractKernels/StreamKernel.hs
src/Futhark/Representation/SegOp.hs
tests/soacs/reduce7.fut
tests/soacs/scan5.fut

This will lower local memory usage for horizontally fused scans.

Keep distinct scan operators, as we do with reduce.

---

CHANGELOG.md
src/Futhark/CodeGen/ImpGen.hs
src/Futhark/CodeGen/ImpGen/Kernels.hs
src/Futhark/CodeGen/ImpGen/Kernels/Base.hs
src/Futhark/CodeGen/ImpGen/Kernels/SegHist.hs
src/Futhark/CodeGen/ImpGen/Kernels/SegRed.hs
src/Futhark/CodeGen/ImpGen/Kernels/SegScan.hs
src/Futhark/CodeGen/ImpGen/Multicore.hs
src/Futhark/CodeGen/ImpGen/Multicore/SegHist.hs
src/Futhark/CodeGen/ImpGen/Multicore/SegRed.hs
src/Futhark/CodeGen/ImpGen/Multicore/SegScan.hs
src/Futhark/Pass/ExpandAllocations.hs
src/Futhark/Pass/ExplicitAllocations/Kernels.hs
src/Futhark/Pass/ExtractKernels.hs
src/Futhark/Pass/ExtractKernels/BlockedKernel.hs
src/Futhark/Pass/ExtractKernels/DistributeNests.hs
src/Futhark/Pass/ExtractKernels/Intragroup.hs
src/Futhark/Pass/ExtractKernels/StreamKernel.hs
src/Futhark/Pass/ExtractMulticore.hs
src/Futhark/Representation/SegOp.hs
tests/soacs/reduce7.fut
tests/soacs/scan5.fut

SegScan now has about the same design as SegReds.  I have not changed the code generation much, so OptionPricing will now crash the compiler.  However, the scan and reduce operators will no longer have memory operands!

Multicore vector scans

---

docs/language-reference.rst

The reference includes `loop pat = initial = while cond do loopbody`.
I believe the second `=` should not be there.

Fix typo in the language reference

---

CHANGELOG.md
src/Language/Futhark/TypeChecker/Terms.hs
tests/overflowing_lits.fut
tests/overflowing_lits0.fut
tests/overflowing_lits1.fut
tests/overflowing_lits2.fut

Resolves #979 
Areas where this PR falls short:
* It adds an extra traversal.
* I would have liked to include a test that it didn't warn for e.g. `-128 : i8` (interesting since the sub-expression of +128 is out of bounds).  I don't think this is possible with the current test setup.
* For the program `let main : f64 = 1e400`, it warns `Literal Infinity out of bounds`.  This isn't fixable without changes to the AST/parser.
* It doesn't warn for type-postfixed literals like `100000u8`, since these are truncated by the parser.  This isn't fixable without changes to the AST/parser.

Warn on out-of-bounds literals

---

src/Futhark/CodeGen/Backends/MulticoreC.hs
src/Futhark/CodeGen/ImpCode/Multicore.hs

The only difference between "cached memory" and ordinary memory is whether or not we look at the `.mem` field when we write it into the struct.  We also no longer propagate cached memory into parallel loops - these are just turned into memory blocks with NULL reference count (in principle we can do a little better than this, but I'm not sure it's worth it).

Fix the memory confusion.

---

rts/c/cuda.h
rts/c/free_list.h
rts/c/opencl.h

Worst case, this means we push a fresh allocation to later rather than
now, so it should not have any negative consequences.
That said, our free list logic is still fairly crude, and there is
likely room for further refinement.
With this change, the performance impact of #1003 drops to just the extra copies.

Let the allocator use memory blocks with right size but wrong tag.

---

src/Futhark/Analysis/PrimExp/Generalize.hs
src/Futhark/CodeGen/Backends/GenericC.hs
src/Futhark/IR/Mem.hs
src/Futhark/IR/Mem/IxFun.hs
src/Futhark/Pass/ExplicitAllocations.hs
tests/existential-loop/rotate.fut
tests/existential-loop/slice.fut

The approach here is to always existentialize or generalize as much of the array
type and index function as possible. Therefore, the technique is a bit different
from the technique used to avoid copies in `if` branches, where we explicitly
try to do the least amount of generalization possible. The approach taken here
is simpler, but leads to more existentials. We therefore rely on the simplifier
to remove some of the invariant loop returns.
For this to work, we need to relax the type checker a bit. We also fixed a bug
in the imperative code generator that didn't handle ScalarSpace correctly.
Here's the resulting benchmark differences from master:
```
futhark-benchmarks/accelerate/canny/canny.fut
data/lena512.in:                                                      0.99x
data/lena256.in: …
```

Existentialize loop returns in order to eliminate some unnecessary copies

---

CHANGELOG.md
src/Futhark/Pass/ExtractKernels.hs
src/Futhark/Pass/ExtractKernels/DistributeNests.hs
src/Futhark/Pass/ExtractKernels/Intragroup.hs
tests/attributes/sequential_outer1.fut
tests/distribution/distribution0.fut
tests/distribution/distribution1.fut
tests/distribution/distribution10.fut
tests/distribution/distribution12.fut
tests/distribution/distribution2.fut
tests/distribution/distribution3.fut
tests/distribution/distribution4.fut
tests/distribution/distribution5.fut
tests/distribution/distribution8.fut
tests/distribution/icfp16-example.fut
tests/distribution/irregular0.fut
tests/distribution/loop6.fut
tests/distribution/redomap0.fut
tests/streamRed_interchange.fut
tests/tiling/seqloop_1d.fut
tests/tiling/seqloop_2d.fut
tests/tiling/tiling_1d_complex.fut

Moderate flattening is completely gone - instead, you can use
attributes to control parallelisation, if needed.
I expect this will have problems and require lots of tweaking, but it
is time we address it directly.
Compile times are harmed, of course.  I hope that is offset by the
significant improvements we've made to compile times recently (and
besides, most of the time is currently spent before kernel extraction,
during inlining, which this change does not affect).
This commit also makes minor changes to the heuristics we use to prune
the multi-versioning tree.  Nothing major, but I expect it will also
require more tuning.

Perform incremental flattening by default.

---

rts/python/scalar.py
src/Futhark/Analysis/PrimExp.hs
src/Futhark/CodeGen/Backends/CCUDA/Boilerplate.hs
src/Futhark/CodeGen/Backends/COpenCL/Boilerplate.hs
src/Futhark/CodeGen/Backends/PyOpenCL.hs
src/Futhark/CodeGen/Backends/SimpleRep.hs
src/Futhark/CodeGen/ImpCode/OpenCL.hs
src/Futhark/CodeGen/ImpGen/Kernels/ToOpenCL.hs
src/Futhark/Construct.hs
src/Futhark/IR/Primitive.hs
src/Futhark/IR/Prop.hs
src/Futhark/IR/Syntax.hs
src/Futhark/Internalise.hs
src/Futhark/Optimise/Simplify/Engine.hs
src/Futhark/Optimise/Simplify/Rules.hs
src/Futhark/Optimise/TileLoops.hs
src/Futhark/Pass/KernelBabysitting.hs
src/Language/Futhark/Interpreter.hs
tests/hoist-unsafe2.fut

Used when hoisting them out of loops.
Closes #1009.

Add safe variants of division operators.

---

rts/c/cuda.h
rts/c/free_list.h
rts/c/opencl.h

Instead, let's try to find the already allocated block that has the best fit.
Here's a benchmark run comparing to the current master:
```
/home/jxk588/src/futhark $ ./tools/cmp-bench-json.py bench-master.json bench-just-size.json
futhark-benchmarks/accelerate/canny/canny.fut
data/lena512.in:                                                      1.16x
data/lena256.in:                                                      1.13x
futhark-benchmarks/accelerate/crystal/crystal.fut
#0 ("200i32 30.0f32 5i32 1i32 1.0f32"):                               0.97x
#4 ("2000i32 30.0f32 50i32 1i32 1.0f32"):                             1.00x
#5 ("4000i32 30.0f32 50i32 1i32 1.0f32"):                             1.00x
futhark-benchmarks/accelerate/fft/fft.fut
data/64x256.in: …
```

Disregard tags when finding free allocs

---

src/Futhark/CLI/Autotune.hs

For incremental flattening, Futhark uses a default threshold in OpenCL GPU
programs of 32768. Some programs and benchmarks (bfast in partcular) have higher
degrees of parallelism for some combinations of threshold and dataset. To
correctly tune threshold parameters, the autotuner assumes that any unset
thresholds will always block execution of the guarded code version, but if the
default threshold is not high enough, that's not always the case. This commit
fixes that, by explicitly setting the default threshold parameter to
2000000000, which is `thresholdMax` in the tuner.
This commit should fix the autotuning problems we've been having with the bfast
benchmark.

Set default threshold size to 2000000000 when autotuning

---

src/Futhark/CodeGen/Backends/CCUDA.hs
src/Futhark/CodeGen/Backends/CCUDA/Boilerplate.hs
src/Futhark/CodeGen/Backends/COpenCL/Boilerplate.hs
src/Futhark/CodeGen/Backends/PyOpenCL/Boilerplate.hs
src/Futhark/CodeGen/ImpGen/Kernels.hs
src/Futhark/CodeGen/ImpGen/Kernels/ToOpenCL.hs
src/Futhark/IR/Kernels/Sizes.hs
src/Futhark/Pass/ExtractKernels.hs

Makes the default threshold generated for intra-group much smaller (32).
This is based on the principle that intra-group is always worth using
(at least by default), as long as the groups are not too tiny.

Use inner parallelism when for intra-group threshold comparisons.

---

src/Futhark/Optimise/InliningDeadFun.hs
src/Futhark/TypeCheck.hs

This reverts commit 0abf01a3e0c623351b25f9b4d18d4d2aa01584b1.
This was to work around limitations in inlining, but I don't think
this is the right way to go about it.  And in fact, the problem goes
away if you apply copy propagation after inlining, which we do now.

Revert "Stricter type checking."

---

stack.yaml

When building from source on Mac with Stack there is a build warning.
```~/CS/forks/futhark/src$ stack build
futhark-0.17.0: unregistering (local file changes: src/futhark.hs)
futhark> configure (lib + exe)
Configuring futhark-0.17.0...
futhark> build (lib + exe)
Preprocessing library for futhark-0.17.0..
Building library for futhark-0.17.0..
Preprocessing executable 'futhark' for futhark-0.17.0..
Building executable 'futhark' for futhark-0.17.0..
/Users/philiplassen/CS/forks/futhark/<built-in>:15:10: error:
warning: non-portable path to file '".stack-work/dist/x86_64-osx/Cabal-3.0.1.0/build/Futhark/autogen/cabal_macros.h"'; specified path differs in case from file name on disk [-Wnonportable-include-path]
#include ".stack-work/dist/x86_64-osx/Cabal-3.0.1.0/build/futhark/autogen/cabal_macr …
```

Fix build warning on MacOS

---

src/Futhark/CodeGen/ImpGen/Kernels.hs
src/Futhark/CodeGen/ImpGen/Kernels/Transpose.hs

I think that support was a relic of an old coalescing optimisation
that we no longer do.

Simplify transpose kernel by no longer supporting jagged arrays.

---

default.nix
futhark.nix
nix/sources.json
nix/sources.nix
shell.nix
src/Language/Futhark/Interpreter.hs

Update sources, niv script, and use manually generated futhark.nix file instead of relying on callCabal2Nix. Needed for #1078.

Update nix scripts

---

futhark.cabal
futhark.nix
src/Futhark/Actions.hs
src/Futhark/Analysis/PrimExp.hs
src/Futhark/CLI/Dev.hs
src/Futhark/IR/Aliases.hs
src/Futhark/IR/Decorations.hs
src/Futhark/IR/Kernels/Kernel.hs
src/Futhark/IR/Kernels/Sizes.hs
src/Futhark/IR/Mem.hs
src/Futhark/IR/Mem/IxFun.hs
src/Futhark/IR/Primitive.hs
src/Futhark/IR/Prop.hs
src/Futhark/IR/Prop/Names.hs
src/Futhark/IR/SOACS/SOAC.hs
src/Futhark/IR/SegOp.hs
src/Futhark/IR/Syntax.hs
src/Futhark/IR/Syntax/Core.hs
src/Futhark/Optimise/Simplify/Lore.hs
src/Language/Futhark/Core.hs
stack.yaml
unittests/Futhark/IR/PrimitiveTests.hs

The purpose of this PR is to allow users to inspect and modify the IR of a program using `futhark dev`. 
We introduce a number of new features to `futhark dev`:
- Writing the output result as an sexp using the `--sexp` flag.
- When reading files, `futhark dev` will distinguish between files ending in `.fut` and files ending in `.sexp`. If a file ends in `.sexp`, `futhark dev` will use the sexp based decoder to decode the IR in the file.
- Added `--compile-opencl` and `--compile-c` flags, to allow users to compile modified IR using the sexp based notation.
There is plenty of room for improvement in the representation that I've made, and sexp-grammar should allow for a much nicer language than what we have now, but I wanted to get this merged so I can actually start using it in my …

Add sexp-based representation for Futhark IR

---

src/Futhark/Analysis/PrimExp.hs
src/Futhark/CodeGen/Backends/COpenCL.hs
src/Futhark/CodeGen/Backends/GenericC.hs
src/Futhark/CodeGen/ImpCode.hs
src/Futhark/CodeGen/ImpGen.hs
src/Futhark/CodeGen/ImpGen/Kernels.hs
src/Futhark/CodeGen/ImpGen/Kernels/Base.hs
src/Futhark/CodeGen/ImpGen/Kernels/SegMap.hs
src/Futhark/CodeGen/ImpGen/Kernels/SegRed.hs
src/Futhark/CodeGen/ImpGen/Kernels/Transpose.hs
tests/big.fut
tests/intragroup/big0.fut

This is not a complete solution to #134, because individual array
dimensions must still fit in a signed 32-bit integer.  However, it
does allow the product of dimensions to be large.

Use 64-bit arithmetic for computing array offsets.

---

shell.nix

ghcid is an alternative to a full IDE environment. When running, it
incrementally builds futhark every time you make a change.

Add ghcid to shell.nix

---

CHANGELOG.md
src/Futhark/Analysis/SymbolTable.hs
src/Futhark/Optimise/Simplify/Engine.hs
src/Futhark/Optimise/Simplify/Rules.hs
tests/loops/loop15.fut
tests/loops/loop16.fut

Detect more complex invariant loop parameters.

---

CHANGELOG.md
futhark.cabal
src/Futhark/CodeGen/ImpGen.hs
src/Futhark/CodeGen/ImpGen/Kernels.hs
src/Futhark/CodeGen/ImpGen/Transpose.hs

This is a good bit faster in many cases, but a bit slower for small
arrays.  Maybe we can special case those later.

Use cache-oblivious transpose on CPU.

---

CHANGELOG.md
src/Language/Futhark/TypeChecker/Terms.hs

Also changes the rules for warning about type defaulting, so that only
types that propagate to the top-level binding are warned about.
Otherwise we would get an ambiguity warning for every instance of
`x[0]`.
Closes #1122.

Permit array indexing with any integer type.

---

.github/workflows/main.yml

The `add-path` method of adding stuff to $PATH has been deprecated.
More info:
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files
https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#adding-a-system-path

Use $GITHUB_PATH instead of add-path

---

src/Futhark/CLI/Datacmp.hs

Added some error checking for the case where bad files are provided. The previous error message when a non-existent file path was provided was 
```
futhark datacmp test.data nonexistant.data
```
gives
```
Internal compiler error (unhandled IO exception).
Please report this at https://github.com/diku-dk/futhark/issues
nonexistant.data: openBinaryFile: does not exist (No such file or directory)
```
With the changes the same input gives the following message. 
```
futhark datacmp test.data nonexistant.data          
```
```
No such file : nonexistant.data
```
This omits the whole internal compiler error / please report thing

Add error handling for bad file paths

---

src/Futhark/CodeGen/Backends/COpenCL.hs

I think this could be helpful when reading debug output of programs with many thresholds.

Add result of comparison to debug output

---

src/Futhark/CodeGen/Backends/SimpleRep.hs

long long is guaranteed to at least be 64 bit. In Emscripten long is only 32 bit. This might also be useful in the case of other archaic platforms.

Change ctzl to ctzll

---

src/Futhark/CLI/Bench.hs
src/Futhark/CLI/Test.hs

Before this change
```
$ futhark test
┌──────────┬────────┬────────┬───────────┐
│          │ passed │ failed │ remaining │
├──────────┼────────┼────────┼───────────┤
│ programs │ 0      │ 0      │ 0/0       │
├──────────┼────────┼────────┼───────────┤
│ runs     │ 0      │ 0      │ 0/0       │
└──────────┴────────┴────────┴───────────┘
$ futhark bench
Reporting average runtime of 10 runs for each dataset.
```
After the change 
```
$ futhark test
Usage: futhark test options... programs...
Options:
-V      --version                   Print version information and exit.
-h      --help                      Print help and exit.
-t      --typecheck                 Only perform type-checking
-i      --interpreted               Only interpret
-c      --compiled                  Only run compiled …
```

No arg fix

---

src/Futhark/Bench.hs
src/Futhark/CLI/Bench.hs
src/Futhark/CodeGen/Backends/CCUDA/Boilerplate.hs
src/Futhark/CodeGen/Backends/GenericC.hs
src/Futhark/CodeGen/Backends/MulticoreC.hs
src/Futhark/CodeGen/Backends/SequentialC.hs
tools/cmp-bench-json.py
unittests/Futhark/BenchTests.hs

This commit adds support for benchmarking memory usage. It does so by changing `futhark bench` to always run with `-P`, and parses the output, searching for memory information. If any is found, it is added to the json output.
I've also added support in tools/cmp-bench-json.py for reporting the memory usage improvements, if present and significant.

Add memory info to futhark bench json output

---

src/Futhark/CodeGen/Backends/GenericPython.hs

This fixes the buildbot failure caused by #1215:
http://buildbot.futhark-lang.org/#/builders/11/builds/1149/steps/14/logs/stdio

Add the -L flag to python backends

---

src/Language/Futhark/Interpreter.hs
tests/rotate0.fut

I believe this should make the interpreters rotation have the expected behaviour and fix the issue in #1235.

Fix rotation in interpreter

---

docs/language-reference.rst
docs/man/futhark-dataset.rst
docs/man/futhark-test.rst

Bit unrelated, but I found it surprising that while any signed type can be used to index an array, only `i64` can be used to slice an array. The docs mention the latter, but "array index must always be of type `i64`" implies that code like `a[0i8]` shouldn't work.
On that note, perhaps it should be more clearly stated somewhere that indexes are `i64`. Unless I've missed something, it's only mentioned in:
* The blog posts about switching to 64-bit indexes
* Chapter 2 of the Futhark book: "Size parameters are always of type `i64`"
* Chapter 3 of the Futhark User's Guide: `3.4.3.9. a[i:j:s]` and `3.4.3.21. e : t` under the "Semantics of Simple Expressions" (Also, the language grammar for `index` implies that any `exp` is valid, though maybe the grammar only cares about syntax and not …

Use i64 indexes, fix stringlit definition

---

src/Futhark/CLI/Dev.hs
src/Futhark/Compiler.hs

This flag disables type checking after each pass when running `futhark
dev`.
It can be useful when manipulating the IR directly.
Suggestions for a better name are welcome.

Add `--no-check` flag to `futhark dev`

---

rts/c/tuning.h

If a tuning file has an unknown name that is shorter than 13 characters (probably won't happen in practice, but it might eventually), then `snprintf` will overwrite past `eql+1`, which results in part of `Unknown name '` being printed as the name. For example, a tuning file with `abcd=` will print `Unknown name 'wn n' on line 1.`:
```
+-- eql+1
v
line    : abcd=
strncpy : abcd=abcd
snprintf: Unknown name '
^^^^
```
The extra `malloc` could be avoided by copying the name to at least 13 characters past `line`, but that seems more complicated.
`max_line_len + 50` is to handle the worst case of a 1022 character name, the format string, and a 9 digit line number (assuming `int` is 32 bits). Might be unnecessary, honestly, since no names will be that long in practice.

Fix unknown tuning name error for short names

---

docs/man/futhark-bench.rst
docs/man/futhark-test.rst
tests/man/bench/example1.fut
tests/man/test/example1.fut
tests/man/test/example2.fut
tests/man/test/example3.fut

I think there are some uncaught mistakes. In the man pages, specifically with regards to `futhark-test`. 
The first program example gives the following when run with vanilla `futhark test`
```
futhark test example1.fut
example1.fut:
Compiling with --backend=c:
Running compiled program:
Running ./example1:
Entry point: main; dataset: #1 ("[4i32, 3i32, 2i32, 1i32] 5i64"):
Expected error:
Assertion.*failed
Got error:
Error: Index [5] out of bounds for array of shape [4].
Backtrace:
-> #0  example1.fut:10:3-6
#1  example1.fut:9:1-10:6
┌──────────┬────────┬────────┬───────────┐
│          │ passed │ failed │ remaining │
├──────────┼────────┼────────┼───────────┤
│ programs │ 0      │ 1      │ 0/1       │
├──────────┼────────┼────────┼───────────┤
│ runs     │ 1      │ 1      │ 0/2       │ …
```

fix futhark-test examples in docs, and add tests.

---

src/Futhark/IR/Kernels/Sizes.hs

Otherwise autotune stops working.
Fixes #1269

Threshold sizes should all be printed on one line

---

rts/python/scalar.py
rts/python/server.py
rts/python/values.py
src/Futhark/CodeGen/Backends/PyOpenCL.hs

Fix for issue #1281: replaced deprecated NumPy types: np.bool => bool (built-in) and np.long => np.int64.

Pyopencl typedeprecation issue1281

---

src/Futhark/IR/SOACS/SOAC.hs
src/Futhark/IR/SOACS/Simplify.hs
src/Futhark/Optimise/Fusion/LoopKernel.hs
tests/issue1284.fut

The SOAC simplifier assumed that there was always just one index value per
output value. Since 624c7f77a and the associated #1258 that is no longer the
case.
Fixes #1284

Correctly handle multi-dimensional scatters when simplifying and fusing

---

rts/python/values.py

In the case where there is no regex match for m, `None` is returned. I don't believe this is expected behaviour, as it means that the type passed in is not a futhark type. In the case of a partial regex match an exception is thrown. 
Unrelated, the last line of the old implementation was a return statement that would never be reached. 
I have rewritten the function to fix both things.

Remove uncalled return statement; add check for non matched regex

---

src/Futhark/Pass/ExtractKernels.hs

There might still be gaps in the parameter numbering due to pruning
done during memory expansion.

Only generate those threshold parameters that are actually used.

---

src/Futhark/CodeGen/Backends/GenericC.hs

Weirdly when Futhark's generated C code is compiled with MacOS, we get the following warning...
```
$ clang min.c
min.c:9:32: warning: unknown warning group '-Wunused-but-set-variable', ignored [-Wunknown-warning-option]
#pragma GCC diagnostic ignored "-Wunused-but-set-variable"
^
1 warning generated.
```
On further inspection it seems that MacOS or clang weidly defines `__GNUC__`
With the following clang version
```
$ clang --version
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin20.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
``` 
Inspecting the predefined macros with clang
```
$ clang -dM -E - < /dev/null | grep GNUC
#define __GNUC_MINOR__ 2
#define __GNUC_PATCHLEVEL__ 1
#define __GNUC_STDC_INLINE__ 1
#define __GNUC__ 4 …
```

Suppress clang warnings fix

---

src/Futhark/Analysis/UsageTable.hs
src/Futhark/CodeGen/ImpGen.hs
src/Futhark/CodeGen/ImpGen/GPU/Base.hs
src/Futhark/Construct.hs
src/Futhark/IR/Mem.hs
src/Futhark/IR/Parse.hs
src/Futhark/IR/Pretty.hs
src/Futhark/IR/Prop/Aliases.hs
src/Futhark/IR/Prop/TypeOf.hs
src/Futhark/IR/Syntax.hs
src/Futhark/IR/Traversals.hs
src/Futhark/Optimise/BlkRegTiling.hs
src/Futhark/Optimise/Fusion.hs
src/Futhark/Optimise/InPlaceLowering.hs
src/Futhark/Optimise/InPlaceLowering/LowerIntoStm.hs
src/Futhark/Optimise/Simplify/Rules/BasicOp.hs
src/Futhark/Optimise/Simplify/Rules/Simple.hs
src/Futhark/Pass/ExtractKernels/DistributeNests.hs
src/Futhark/Transform/FirstOrderTransform.hs
src/Futhark/TypeCheck.hs

Useful for AD and also makes sequentialisation of scatter nicer.  Not
exposed in source language for now.

Support scatter-like bounds checking for Update.

---

src/Futhark/CLI/Dev.hs
src/Futhark/CLI/Test.hs
tools/testparser.sh

So:
* '--gpu' is what used to be '--kernels'
* '--gpu-mem' is what used to be '--gpu'
* '--mc-mem' is what used to be '--multicore'
* '--seq-mem' is what used to be '--cpu'.
For input file names:
* '.fut_gpu' is what used to be '_fut_kernels'
* '.fut_gpu_mem' is what used to be '.fut_kernels_mem'
@munksgaard and @coancea: you will care about this.
Time to update years of muscle memory!

Make 'futhark dev' use the correct representation names.

---

src/Futhark/CodeGen/ImpGen.hs
src/Futhark/CodeGen/ImpGen/GPU.hs
src/Futhark/CodeGen/ImpGen/GPU/Base.hs
src/Futhark/CodeGen/ImpGen/GPU/SegHist.hs
src/Futhark/CodeGen/ImpGen/Multicore/Base.hs

Any slicing now needs to be done on the MemLocs in advance, changing
the index function.

 Remove Slices from the ImpGen CopyCompiler. 

---

src/Futhark/CodeGen/Backends/MulticoreC.hs
src/Futhark/CodeGen/Backends/MulticoreWASM.hs

This code duplication fell through the cracks.

Deduplicate generateContext in multicore WASM and Multicore C.

---

.github/workflows/main.yml

The Python library tests don't seem to be run by the CI. I'm not sure if this was an oversight or intentional. This PR adds them to the CI.

Add python lib tests to CI

---

src/Futhark/Actions.hs

I'm pretty sure that deleting these lines is a good thing because they aren't needed.
Basically if the output file has a `.mjs` file extension it will automatically compile with `MODULARIZE` and `EXPORT_ES6`. The reason I didn't just commit is because I found out these lines weren't needed from reading Emscripten source code. Namely these [lines](https://github.com/emscripten-core/emscripten/blob/main/emcc.py#L1430-L1442). I can't find any reference to this in the documentation stating this is true. So its dependant on these lines not changing. But its unlikely it will change.
I thought I'd hand it over to you, to make the call.

Remove implicit emcc flags.

---

futhark.cabal
src/Futhark/CLI/Dataset.hs

This is motivated by 'random' being well maintained now.
Generation of float values is slightly slower, while generation of
integers is slightly faster.

Switch from pcg-random to random.

---

src/Futhark/CodeGen/Backends/CCUDA/Boilerplate.hs
src/Futhark/CodeGen/Backends/COpenCL/Boilerplate.hs
src/Futhark/CodeGen/Backends/MulticoreC.hs
src/Futhark/CodeGen/Backends/SequentialC/Boilerplate.hs

This has always been the rule, but it was not checked.  This allowed
some FFI bridges to mistakenly free the config early, which could lead
to subtle memory corruption.
Now at least it will crash loudly.

Assert that context configuration is unused when freed.

---

src/Futhark/CLI/Literate.hs

Previously the literate help message would display an incorrect help message for -o:
```
-o FILE  --output=FILE               Enable logging.  Pass multiple times for more.
```

Improve futhark literate output help message

---

src/Futhark/CLI/Autotune.hs

Detects whether tuning a parameter decreases the performance on a given
dataset. Ideally, this should never happen and (excepting bugs in the autotuner)
is a sign of non-monotonicity in the generated Futhark program.
Fixes #1554.

 Issue a warning if non-monotonicity is detected while autotuning. 

---

src/Futhark/CodeGen/ImpGen/GPU/Base.hs
src/Futhark/IR/GPU/Op.hs
src/Futhark/IR/Parse.hs
src/Futhark/IR/SegOp.hs
src/Futhark/Optimise/BlkRegTiling.hs
src/Futhark/Optimise/TileLoops.hs
src/Futhark/Optimise/TileLoops/Shared.hs
tests/tiling/tiling2.fut
tests/tiling/tiling_2d.fut
tests/tiling/tiling_2d_indirect.fut
tests/tiling/tiling_2d_inner.fut

This is used to simplify register tiling slightly, and might even
result in a performance improvement as there will be fewer barriers.

Support partial sequentialisation of intra-group parallelism.

---

src/Futhark/CodeGen/Backends/MulticoreC.hs
src/Futhark/CodeGen/ImpCode/Multicore.hs
src/Futhark/CodeGen/ImpGen.hs
src/Futhark/CodeGen/ImpGen/Multicore/Base.hs
src/Futhark/CodeGen/ImpGen/Multicore/SegHist.hs
src/Futhark/CodeGen/ImpGen/Multicore/SegMap.hs
src/Futhark/CodeGen/ImpGen/Multicore/SegRed.hs
src/Futhark/CodeGen/ImpGen/Multicore/SegScan.hs

The actual loop is now explicit in the ImpCode, rather than being
inserted during C code generation.  This should give us a little more
flexibility.

Simplify ParLoop in multicore representation.

---

CHANGELOG.md
src/Futhark/CodeGen/Backends/GenericC.hs
src/Futhark/CodeGen/Backends/MulticoreC.hs
src/Futhark/CodeGen/ImpGen/GPU/ToOpenCL.hs

Previously, every error point would contain code to free every memory
block in scope.  This caused significant code duplication.  Now they
jump to a shared function epilogue that frees all memory blocks.
Closes #1584.

Refactor error handling in generated host code.

---

src/Futhark/Optimise/MemoryBlockMerging.hs

This turned out to negatively affect performance. Also, I have renamed the `futhark dev` flag for memory block merging from `--reuse-allocations` to `--memory-block-merging`.

Don't perform memory block merging on ScalarSpace values

---

docs/language-reference.rst
src/Language/Futhark/Parser/Lexer.x

As per the reference, newlines in string literals should not be allowed.

Prohibit newlines in string literals

---

CHANGELOG.md
src/Futhark/CLI/Defs.hs
src/Futhark/CLI/Misc.hs
src/Futhark/CLI/REPL.hs
src/Futhark/Compiler/Program.hs
src/Futhark/Util.hs
src/Language/Futhark/Interpreter.hs
src/Language/Futhark/Semantic.hs
src/Language/Futhark/TypeChecker.hs

I also took the liberty of cleaning up some other parts of how the
REPL works.
This is not as efficient as it could be for the REPL, since only the
type checking is cached.  However, that is good enough for a language
server, which only has the type checking part anyway.

Support program reload cache.

---

src/Futhark/Compiler/Program.hs
src/Language/Futhark/Parser/Lexer.x
src/Language/Futhark/Parser/Lexer/Wrapper.hs
src/Language/Futhark/Parser/Monad.hs
src/Language/Futhark/Parser/Parser.y

The code compiles but the location info are still missing somehow, for example the code below will still emit `NoLoc`:
```futhark
def average (xs: []f64) = reduce (* 0 xs / f64.i64 (length xs)
```
Just managed to trace it back to [parseError](https://github.com/diku-dk/futhark/blob/f18ec76225b4c7c652d3b2148a382b9fbd4c5c36/src/Language/Futhark/Parser/Monad.hs#L241), `NoLoc` starts from there, will keep investigating

Loc info for parse Error

---

src/Futhark/LSP/Compile.hs
src/Futhark/LSP/Diagnostic.hs

This reverts commit cd000141224b7f2fb9634bad85f7b19435c22ee4.
Not sure what's the implementation detail in `lsp` package, but diagnostics are not flushed without `diagnosticSource`.
Re-pro steps:
1. open the correct futhark file
2. trigger an error/warning to get diagnostic
3. fix the problem just triggered
4. the diagnostic won't disappear

lsp: fix diagnostics are not flushed

---

futhark.cabal
src/Futhark/LSP/Compile.hs
src/Futhark/LSP/Handlers.hs
src/Futhark/LSP/PositionMapping.hs
src/Futhark/LSP/State.hs
src/Futhark/LSP/Tool.hs

close #1621  , referencing [deltaFromDiff](https://github.com/haskell/haskell-language-server/blob/7518a3a7eb9c11b2dbbff0aed1d982fd3e3505a9/ghcide/src/Development/IDE/Core/PositionMapping.hs#L185)
The logic for computing mapping and converting between current and stale positions is ready.
But there is still some problems when we navigate between files, should be fixed in another PR probably. Using [heston](https://github.com/diku-dk/futhark-benchmarks/tree/master/misc/heston) for example:
1. Open `heston.fut`
2. Go to def (or simply open) `least_squares.fut` (State will be re-compiled, AST won't have `heston.fut` anymore)
3. Tigger some errors in `least_squares.fut`
4. Go back to `heston.fut` and try to Go to def to `least_squares.fut`

lsp: positionmap when use stale type-checked result

---

.github/workflows/main.yml
HACKING.md
Makefile
README.md
docs/installation.rst
tools/git-hooks/pre-commit
tools/style-check.sh

I like cabal better than stack nowadays, but 'cabal install' is just
so awkward.  So now we have a Makefile frontend!

Deprecate stack; add wrapper Makefile.

---

CHANGELOG.md
docs/language-reference.rst
prelude/array.fut
prelude/zip.fut
src/Language/Futhark/TypeChecker/Terms.hs
src/Language/Futhark/TypeChecker/Terms/DoLoop.hs
src/Language/Futhark/TypeChecker/Terms/Monad.hs
src/Language/Futhark/TypeChecker/Terms/Pat.hs
src/Language/Futhark/TypeChecker/Types.hs
src/Language/Futhark/TypeChecker/Unify.hs
tests/issue1074.fut
tests/issue596.fut
tests/issue728.fut
tests/issue844.fut
tests/issue879.fut
tests/issue880.fut
tests/types/inference32.fut
tests/types/tricky.fut
tests/uniqueness/uniqueness-error14.fut
tests/uniqueness/uniqueness-error22.fut
tests/uniqueness/uniqueness-error27.fut
tests/uniqueness/uniqueness-error33.fut
tests/uniqueness/uniqueness-error34.fut
tests/uniqueness/uniqueness-error35.fut
tests/uniqueness/uniqueness-error48.fut
tests/uniqueness/uniqueness-error49.fut
tests/uniqueness/uniqueness-error51.fut
tests/uniqueness/uniqueness-error59.fut
tests/uniqueness/uniqueness55.fut

I want to eventually move away from the term "uniqueness types" and
recast this language feature as a kind of effect system.
You should never see `*` in non-function types, and they are better
thought of as effect indicators.

Simplify handling of uniqueness.

---

Makefile

If the installation directory does not exist, the futhark binary will be installed as a binary with the name of the destination folder.
For example, by default running `make install` will install futhark at `~/.local/bin/futhark`. If the directory `~/.local/bin/` does not exist, it would be installed as `~/.local/bin`. 
This patch fixes this issue by  specifying  the desired installation name in the Makefile.

Makefile installs futhark in wrong location if destination directory does not exist.

---

src/Futhark/CodeGen/ImpGen/GPU/Base.hs
src/Futhark/CodeGen/ImpGen/GPU/Group.hs
src/Futhark/IR/GPU/Op.hs
src/Futhark/IR/GPU/Simplify.hs
src/Futhark/IR/Parse.hs
src/Futhark/Pass/ExplicitAllocations.hs
src/Futhark/Pass/ExplicitAllocations/GPU.hs
src/Futhark/Pass/ExplicitAllocations/MC.hs
src/Futhark/Pass/ExplicitAllocations/SegOp.hs
src/Futhark/Pass/KernelBabysitting.hs

This is one of the major dividends from removing the parallel Stream
SOAC.

Remove the SplitSpace IR construct and supporting machinery.

---

src/Futhark/CodeGen/Backends/GenericC.hs
src/Futhark/CodeGen/Backends/GenericC/Code.hs
src/Futhark/CodeGen/ImpGen/GPU/ToOpenCL.hs

Previously we would split variable declaration and assignment over two
C statements.  Now they are one.  No performance change, but it's
easier to read.

Generate prettier C code for indexing and calls to builtins.

---

CHANGELOG.md
futhark.cabal
src/Futhark/CLI/REPL.hs
src/Futhark/CLI/Run.hs
src/Futhark/Util/Pretty.hs
src/Language/Futhark/Interpreter.hs
src/Language/Futhark/Interpreter/Values.hs

This change looks bigger than it really is, because I also took the
opportunity to move the interpreter value representation to a separate
module.  The idea is to further separate out non-monadic operations on
values.
Closes #1724.

Avoid type suffixes on values printed in REPL.

---

src/Futhark/CodeGen/ImpGen/GPU.hs
src/Futhark/CodeGen/ImpGen/GPU/Base.hs
src/Futhark/CodeGen/ImpGen/GPU/Group.hs
src/Futhark/CodeGen/ImpGen/GPU/SegHist.hs
src/Futhark/CodeGen/ImpGen/GPU/SegMap.hs
src/Futhark/CodeGen/ImpGen/GPU/SegRed.hs
src/Futhark/CodeGen/ImpGen/GPU/SegScan/SinglePass.hs
src/Futhark/CodeGen/ImpGen/GPU/SegScan/TwoPass.hs
src/Futhark/IR/GPU/Op.hs
src/Futhark/IR/Parse.hs
src/Futhark/Optimise/BlkRegTiling.hs
src/Futhark/Optimise/GenRedOpt.hs
src/Futhark/Optimise/ReduceDeviceSyncs/MigrationTable.hs
src/Futhark/Optimise/TileLoops.hs
src/Futhark/Optimise/TileLoops/Shared.hs
src/Futhark/Pass/ExpandAllocations.hs
src/Futhark/Pass/ExplicitAllocations/GPU.hs
src/Futhark/Pass/ExtractKernels/Intragroup.hs
src/Futhark/Pass/ExtractKernels/StreamKernel.hs
src/Futhark/Pass/ExtractKernels/ToGPU.hs
tests/tiling/tiling_1d.fut
tests/tiling/tiling_2d.fut

Now we have three levels: SegThread, SegGroup, and SegThreadInGroup.
Also, the specification of the grid size has been decoupled and made optional.  This allows us to generate flat parallelism without being forced to worry about the low-level details of how many threads to launch (although flattening will still presently mostly do that).  We still have freedom to decide if we wish, for example in tiling, which has also been slightly rewritten.

Refactor SegLevel for GPU representation.

---

.gitignore

The two first lines of our .gitignore explicitly unignore the .git folder.
This creates problems for tools such as ripgrep which rely on parsing the .gitignore file. See for instance the discussion here: https://github.com/BurntSushi/ripgrep/issues/2329
On another note, perhaps we might want to get rid of those two lines? As an alternative, we could codify that the /scratch directory is ignored, and could be used for the same purpose as the root directory currently is.

Add .git to .gitignore

---

src/Futhark/CodeGen/Backends/GenericC/Fun.hs
src/Futhark/CodeGen/ImpCode.hs
src/Futhark/CodeGen/ImpGen/GPU/ToOpenCL.hs

Only implemented for GPU backends.
This cuts down on control flow (and thus overhead) for function calls.
Can in principle also be generalised to work with ISPC and CPU backends, but that's not part of this PR.

Compile very simple functions without error error return code.

---

src/Futhark/CodeGen/ImpGen/GPU/SegHist.hs

Previously we would create a lock for every single element, but this is wasteful (and unnecessary) in the case of vectorised operators, where we (at least currently) take the lock based only on the non-vector indexes.
It might be worth changing that (as it would cause less lock contention), and then this commit would have to be reverted.

Correct number of locks for local memory case.

---

CHANGELOG.md
rts/c/opencl.h
rts/python/opencl.py
src/Futhark/CodeGen/Backends/CCUDA.hs
src/Futhark/CodeGen/Backends/COpenCL.hs
src/Futhark/CodeGen/Backends/GenericC/Pretty.hs
src/Futhark/CodeGen/Backends/PyOpenCL.hs
src/Futhark/CodeGen/ImpCode/GPU.hs
src/Futhark/CodeGen/ImpCode/OpenCL.hs
src/Futhark/CodeGen/ImpGen/GPU/Base.hs
src/Futhark/CodeGen/ImpGen/GPU/SegHist.hs
src/Futhark/CodeGen/ImpGen/GPU/ToOpenCL.hs
src/Futhark/CodeGen/ImpGen/GPU/Transpose.hs
src/Futhark/IR/Prop/Names.hs

In principle this allows better register allocations for OpenCL kernels.  If nothing else, it fixes cases where the NVIDIA OpenCL implementation would use so many registers that we couldn't even launch the kernel with a large group size.

Generate reqd_work_group_size for OpenCL kernels.

---

CHANGELOG.md
src/Futhark/CodeGen/ImpGen/Multicore/SegScan.hs

The old codegen was truly weird, and executed the kernel body multiple times.  There is still room to improve, but it is much saner now.
Fixes #1777.

Fix multicore codegen for scan.

---

docs/man/futhark-literate.rst
src/Futhark/CLI/Literate.hs
tests_literate/audio.fut
tests_literate/expected/audio.md

So far it only handles 8-bit audio at 44100 Hz, but we should be able to extend it if needed.

futhark-literate: Add :audio directive

---

CHANGELOG.md
src/Language/Futhark/Parser/Lexer.x
src/Language/Futhark/Parser/Lexer/Tokens.hs
src/Language/Futhark/Parser/Lexer/Wrapper.hs
src/Language/Futhark/Parser/Parser.y
tests/errors/doubleindex.fut
tests/records11.fut

We have long had a Great Parser Hack due to whitespace-sensitivity - 'a[x]' means something very different from 'a [x]'.  This was implemented in a crude way, and now it is implemented in a slightly less crude (and somewhat more robust) way.
The key idea is to treat a '[' following an identifier as a different token from a '[' not following an identifier.
While I was rummaging around in the parser anyway, I also took the liberty to improve our handling of projection, which is now more robust.
One difference is that it is now possible to say 'x . y' for projection (including for module components).  I'm not certain whether this is desirable, but it simplifies the grammar a lot to allow it. SML allows it, too.

Improve the parser somewhat.

---

docs/man/futhark-literate.rst
src/Futhark/CLI/Literate.hs
tests_literate/audio.fut
tests_literate/expected/audio.md

By giving the `audio` directive an array of type `[2][]f32`, you will create stereo audio. The first row is the left channel and the second row is the right channel.

literate-audio: Add support for multiple channels, e.g. stereo

---

futhark.cabal
rts/c/backends/c.h
rts/c/backends/cuda.h
rts/c/backends/multicore.h
rts/c/backends/opencl.h
rts/c/context.h
rts/c/context_prototypes.h
rts/c/util.h
src/Futhark/CodeGen/Backends/CCUDA.hs
src/Futhark/CodeGen/Backends/CCUDA/Boilerplate.hs
src/Futhark/CodeGen/Backends/COpenCL.hs
src/Futhark/CodeGen/Backends/COpenCL/Boilerplate.hs
src/Futhark/CodeGen/Backends/GenericC.hs
src/Futhark/CodeGen/Backends/MulticoreC/Boilerplate.hs
src/Futhark/CodeGen/Backends/SequentialC/Boilerplate.hs
src/Futhark/CodeGen/RTS/C.hs

The goal of this is to move more C code out of code generation and into the RTS, and make it more data driven.  This has several minor benefits:
* It is easier to write large blocks of C code in a C file than inside a Haskell quasiquotation.
* It is easier to test.
* Eventually we will be able to compile the Futhark run-time system separately and link it with code produced by the compiler.  This cuts down on compile times when you have a large number of small programs.  Might also allow linking of Futhark programs, which will allow separate compilation of Futhark.

Disentangle context config from code generation

---

src/Futhark/CodeGen/Backends/CCUDA.hs
src/Futhark/CodeGen/Backends/COpenCL.hs
src/Futhark/CodeGen/Backends/GenericC.hs
src/Futhark/CodeGen/Backends/GenericC/Code.hs
src/Futhark/CodeGen/Backends/GenericC/Monad.hs
src/Futhark/CodeGen/Backends/GenericPython.hs
src/Futhark/CodeGen/Backends/MulticoreISPC.hs
src/Futhark/CodeGen/Backends/PyOpenCL.hs
src/Futhark/CodeGen/ImpCode.hs
src/Futhark/CodeGen/ImpGen.hs
src/Futhark/CodeGen/ImpGen/GPU.hs
src/Futhark/CodeGen/ImpGen/GPU/Base.hs
src/Futhark/CodeGen/ImpGen/GPU/SegHist.hs
src/Futhark/CodeGen/ImpGen/GPU/SegRed.hs
src/Futhark/CodeGen/ImpGen/GPU/SegScan/SinglePass.hs
src/Futhark/CodeGen/ImpGen/GPU/ToOpenCL.hs
src/Futhark/CodeGen/ImpGen/Multicore.hs
src/Futhark/CodeGen/ImpGen/Multicore/SegHist.hs

Instead, just use replicate kernels.  That's faster, but more importantly it lets us simplify the static arrays mechanism, which was always quite hacky.

Do not use static arrays in GPU codegen.

---

CHANGELOG.md
src/Futhark/IR/Mem/Simplify.hs

This is a very old (5+ years) rule that is much too naive in its handling of memory.  We have better optimisations now, that aren't buggy.

Remove copyCopyToCopy rule.

---

src/Futhark/CLI/Doc.hs
src/Futhark/CLI/Misc.hs
src/Futhark/CLI/REPL.hs
src/Futhark/Compiler/Program.hs
src/Futhark/Doc/Generator.hs
src/Futhark/Internalise/Defunctorise.hs
src/Language/Futhark/Interpreter.hs
src/Language/Futhark/Query.hs
src/Language/Futhark/Semantic.hs
src/Language/Futhark/Syntax.hs
src/Language/Futhark/TypeChecker/Monad.hs

Previously some parts of the compiler would use FilePaths directly, and it is ambiguous whether those refer to canonical import names. Now it should be clearer.

Use ImportName consistently.

---

src/Futhark/AD/Rev/SOAC.hs
src/Futhark/Tools.hs
tests/ad/issue1879.fut

Support rev AD of scanomaps and scatters with non-identity lambdas.

---

CHANGELOG.md
cabal.project
docs/manifest.schema.json
docs/server-protocol.rst
futhark.cabal
nix/futhark-manifest.nix
nix/futhark-server.nix
rts/c/server.h
src/Futhark/CLI/Autotune.hs
src/Futhark/CodeGen/Backends/GenericC.hs
src/Futhark/CodeGen/Backends/GenericC/CLI.hs
src/Futhark/CodeGen/Backends/GenericC/EntryPoints.hs
src/Futhark/CodeGen/Backends/GenericC/Server.hs
src/Futhark/CodeGen/Backends/PyOpenCL/Boilerplate.hs
src/Futhark/CodeGen/ImpCode.hs
src/Futhark/CodeGen/ImpCode/OpenCL.hs
src/Futhark/CodeGen/ImpGen/GPU/ToOpenCL.hs

This involves extending the manifest and server protocol, and modifying 'futhark autotune' to use this new information.
The main advantage (apart from general cleanup) is that we can now tune threshold parameters used in non-inlined functions.
Closes #1884.

Record which tuning params are relevant to which entry points.

---

src/Futhark/Internalise/NormaliseSize.hs
src/Language/Futhark/Prop.hs

In particular, it was excessively monadic.  There was no need for the outer monad.  Also, the ArrowArgM did not need to have an inner monad.
You may consider whether ArrowArgM needs to exist at all.  I suspect those functions would be simpler if they were written in a conventional functional style.
Similarly, Writer looks really seductive at first, but it's slow and when things get complicated, code using it is difficult to read (e.g. 'pass').  I used to use it a lot, but now I always use State instead.
It's pretty common for people who are experienced functional programmers, but new to Haskell, to over-monadify their code.

Simplify normalisation pass.

---

CHANGELOG.md
src/Futhark/CodeGen/ImpGen/GPU.hs
src/Futhark/CodeGen/ImpGen/GPU/Transpose.hs

Unfortunately, using 64 bit index arithmetic in all cases results in unacceptable performance for small arrays, so we need this bit of multi-versioning.  Fortunately the transpose kernels are not large.
Fixes #1953.

Use 64-bit transpose kernels for large arrays.

---

src/Futhark/Optimise/Simplify/Engine.hs
src/Futhark/Pass/ExplicitAllocations.hs

This was a somewhat complicated fix for #1309, but with the arrival of single-LMAD index functions, it may no longer be necessary.

Remove simplifyPatFromExpS machinery.

---

rts/c/backends/cuda.h
src/Futhark/CodeGen/Backends/CCUDA.hs
src/Futhark/CodeGen/Backends/CCUDA/Boilerplate.hs

Previously we always used the "default stream", which might also be used by others.
The ultimate goal of this is to make it possible for the user to provide their own stream.

Use own stream in CUDA backend.

---

src/Language/Futhark/Interpreter.hs

This code checks for mismatches in the number of dimensions as well as checking that the length of each dimension is the same. If there is a mismatch a helpful error message is printed.

Add error checking for array dimensions when using interpreter fix #1682

---

src/Futhark/Optimise/ArrayShortCircuiting/ArrayCoalescing.hs
tests/memory-block-merging/coalescing/issue-2010.fut
tests/memory-block-merging/coalescing/lud/lud_internal1-16.fut
tests/memory-block-merging/coalescing/lud/lud_internal1.fut
tests/memory-block-merging/coalescing/lud/lud_internal3.fut
tests/memory-block-merging/coalescing/lud/lud_internal4.fut
tests/memory-block-merging/coalescing/map/map12.fut
tests/memory-block-merging/coalescing/map/map15.fut

When short-circuiting with a function argument as the source, we should verify that the destination is never used in-between the short-circuiting point and the start of the function, because the source is live in all that code.  Instead of
checking for memory overlap, we can simply check that the destination is unused, because we already enforce that the index function of the destination must match the index function of the function argument.
Fixes #2010
This PR also contains a fix to another issue, which caused map short-circuits to incorrectly process the map body after adding the short-circuit target and destination to the current short-circuiting attempt. This led to us to reject some otherwise sound short-circuitings.
Combined with the fix in handling function arguments as …

Check that dst is unused when short-circuiting function args

---

src/Futhark/CLI/REPL.hs

I have added the machinery to print strings with arbitrary expressions within the Futhark REPL. I have yet to add any options for formatting, my first thought is to add formatting code to `Util.Pretty`, but I am open to advice

Format command for REPL #1567

---

CHANGELOG.md
docs/c-api.rst
rts/c/backends/cuda.h
rts/c/backends/hip.h
rts/c/backends/opencl.h
rts/c/context.h
src/Futhark/CodeGen/Backends/GenericC.hs

This simplifies the life of the user, at a small extra copying overhead.
It is particularly useful when calling these functions through an FFI from a garbage collected language, where managing the lifetime of a C string can be quite annoying and error-prone.

Copy strings passed to API functions.

---

Makefile

The command 'make install' should call install command with option '-D', but in macOS, the install command hasn't option '-D'. So, I add a condition at install target in Makefile to detect operate system, if the operate system is macOS, then call install command with option '-d' to create installed directory.

Fix issue of failed run 'make install' in macOS

---

src/Futhark/CodeGen/ImpGen/GPU/SegScan.hs
src/Futhark/CodeGen/ImpGen/GPU/SegScan/SinglePass.hs

This PR adds group virtualization to SegScan.SinglePass. The generated single pass scan code now respects the suggested/requested num_groups/block_size, which in turn allows scanomaps with array construction in the map KernelBody, since mem expansion bases its expansion on this information.
Also
* status flags (for the lookback step) are now initialized inside the kernel
* some light code refactoring

single pass scan group virtualization

---

src/Futhark/CodeGen/Backends/GPU.hs
src/Futhark/CodeGen/Backends/PyOpenCL.hs
src/Futhark/CodeGen/Backends/PyOpenCL/Boilerplate.hs
src/Futhark/CodeGen/ImpCode/GPU.hs
src/Futhark/CodeGen/ImpGen/GPU.hs
src/Futhark/CodeGen/ImpGen/GPU/Base.hs
src/Futhark/CodeGen/ImpGen/GPU/SegHist.hs
src/Futhark/CodeGen/ImpGen/GPU/SegRed.hs
src/Futhark/CodeGen/ImpGen/GPU/SegScan/SinglePass.hs
src/Futhark/CodeGen/ImpGen/GPU/ToOpenCL.hs

This is very tedious code, and required adding the notion of "kernel constant expressions", as we have some expressions that _must_ be constant at kernel compilation time (which is at program runtime). We actually had this notion in the ImpCode representation, but now ImpGen provides some manual control as well.

Query register capacity for segred and segscan codegen.

---

rts/c/scalar.h

The previous commit missed one unguarded `double`. With this, the compiler produces a working program \o/

Really don't talk about double unless needed

---

CHANGELOG.md
docs/language-reference.rst
src/Language/Futhark/Parser/Parser.y
tests/trailing-commas.fut

Support trailing commas.

---

CHANGELOG.md
rts/c/backends/c.h
rts/c/backends/cuda.h
rts/c/backends/hip.h
rts/c/backends/multicore.h
rts/c/backends/opencl.h
rts/c/context.h

There are still a few places where we do OPENCL_SUCCEED_FATAL(), but mostly in places where failure implies something is completely wonky with the system.
Fixes #2077.

Handle failures during OpenCL context init gracefully.

---

src/Futhark/IR/Mem/IxFun.hs
src/Futhark/IR/Mem/LMAD.hs
src/Futhark/IR/Mem/Simplify.hs
src/Futhark/IR/Parse.hs
src/Futhark/Optimise/ArrayShortCircuiting/ArrayCoalescing.hs
src/Futhark/Optimise/ArrayShortCircuiting/MemRefAggreg.hs
src/Futhark/Optimise/BlkRegTiling.hs
src/Futhark/Optimise/DoubleBuffer.hs
src/Futhark/Pass/ExpandAllocations.hs
src/Futhark/Pass/ExplicitAllocations.hs
tests/distribution/loop2.fut
tests/memory-block-merging/coalescing/copy/pos5.fut
tests/memory-block-merging/coalescing/hoisting/copy-in-if.fut
tests/memory-block-merging/coalescing/lud/lud.fut

With this PR, index functions are now just LMADs, with no extra information.
This results in an overall reduction of copies.
However, some of those copies turn out to be load-bearing, so we need
fixes elsewhere, in particular memory expansion.
My hope is that this will lead to the memory handling being simpler
and more intentionally (instead of accidentally) correct.

Remove base from index functions

---

CHANGELOG.md
cabal.project
docs/c-api.rst
docs/manifest.schema.json
futhark.cabal
nix/futhark-manifest.nix
src/Futhark/CodeGen/Backends/GenericC/CLI.hs
src/Futhark/CodeGen/Backends/GenericC/Server.hs
src/Futhark/CodeGen/Backends/GenericC/Types.hs
src/Futhark/CodeGen/ImpGen.hs
src/Futhark/IR/Parse.hs
src/Futhark/IR/Pretty.hs
src/Futhark/IR/Syntax/Core.hs
src/Futhark/IR/TypeCheck.hs
src/Futhark/Internalise/Entry.hs
src/Futhark/Internalise/TypesValues.hs
tests_lib/c/project.fut
tests_lib/c/sum.fut
tests_lib/c/test_project.c
tests_lib/c/test_sum.c

Construction and destruction of sum values in C API.

---

src/Futhark/IR/Mem/Simplify.hs

This rather complicated and dubiously sound simplification rule has long been necessary as a workaround for deficiencies elsewhere in the compiler. With the recent improvements to double buffering and memory expansion (and the general simplification of the memory representation), it may no longer be necessary. Performance impact of the removal is unclear, but the test suite works.

Remove unExistentialiseMemory.

---

CHANGELOG.md
docs/conf.py
docs/index.rst
docs/man/futhark-literate.rst
docs/man/futhark-script.rst
futhark.cabal
src/Futhark/CLI/Literate.hs
src/Futhark/CLI/Main.hs
src/Futhark/CLI/Script.hs
src/Futhark/Script.hs

I expect this will mainly be useful for compiler debugging, as a replacement for running executables. This allows us to directly run the executables produced by 'futhark bench'.

New tool: futhark script.

---

futhark.cabal
src/Futhark/Internalise/Monomorphise.hs
src/Language/Futhark/TypeChecker.hs
src/Language/Futhark/TypeChecker/Monad.hs
src/Language/Futhark/TypeChecker/Names.hs
src/Language/Futhark/TypeChecker/Terms.hs
src/Language/Futhark/TypeChecker/Terms/Loop.hs
src/Language/Futhark/TypeChecker/Terms/Monad.hs
src/Language/Futhark/TypeChecker/Terms/Pat.hs
src/Language/Futhark/TypeChecker/Types.hs
unittests/Language/Futhark/TypeChecker/TypesTests.hs

This is to make the type checker more modular and ultimately switch to a constraint-based solver.

Perform name resolution in separate type checking pass.

---

CHANGELOG.md
futhark.cabal
src/Futhark/CLI/Dev.hs
src/Futhark/Internalise.hs
src/Futhark/Internalise/ApplyTypeAbbrs.hs
src/Futhark/Internalise/FullNormalise.hs
src/Futhark/Internalise/LiftLambdas.hs
src/Futhark/Internalise/Monomorphise.hs
tests/issue2106.fut

This looks a lot more complicated than it ought to. The real bug was a mishandling of local polymorphic functions in monomorphisation. I reasoned that there is no reason monomorphisation should ever encounter those - we should lambda lift those before we monomorphise. However, that created the need for a bunch of other modifications, including a new (very small) pass (ApplyTypeAbbrs) that runs just after defunctorisation.
IT is overall a conceptual simplification, but the code changes look quite large for such a small bug.

Fix #2106.

---

CHANGELOG.md
docs/c-api.rst
rts/c/backends/cuda.h
rts/c/backends/hip.h
rts/c/backends/opencl.h
src/Futhark/CodeGen/Backends/GPU.hs

This partially offsets #2112, but is mostly intended for hybrid execution.

Add support for unified memory allocations

---

src/Futhark/AD/Fwd.hs
src/Futhark/AD/Rev.hs
src/Futhark/AD/Rev/Monad.hs
src/Futhark/CodeGen/ImpGen.hs
src/Futhark/CodeGen/ImpGen/GPU/Base.hs
src/Futhark/CodeGen/ImpGen/GPU/Block.hs
src/Futhark/CodeGen/ImpGen/Multicore.hs
src/Futhark/IR/Parse.hs
src/Futhark/IR/Pretty.hs
src/Futhark/IR/Prop/Aliases.hs
src/Futhark/IR/Prop/TypeOf.hs
src/Futhark/IR/Syntax.hs
src/Futhark/IR/Traversals.hs
src/Futhark/IR/TypeCheck.hs
src/Futhark/Internalise/Exps.hs
src/Futhark/Optimise/BlkRegTiling.hs
src/Futhark/Optimise/GenRedOpt.hs
src/Futhark/Optimise/HistAccs.hs
src/Futhark/Optimise/Simplify/Rules.hs
src/Futhark/Optimise/Simplify/Rules/BasicOp.hs
src/Futhark/Pass/ExtractKernels/Interchange.hs

Adds support for unsafe `UpdateAcc` ops, to omit boundary checks on the accumulator in cases where the indices are known (or assumed) to always be within bounds. The initial motivation was to use `WithAcc` to read block/register tiles from global to shared memory in the (WIP) tensor contraction tiling, wherein I would like to handle boundaries manually (if at all).
In most places, I simply took inspiration from the existing `Update` cases.
TODOs:
1) In those places in the compiler where `UpdateAcc` ops are passed along,
I simply pass on the existing `Safety` information. I cannot discern
whether there may be cases where an optimization or transformation
enables or necessitates changing the `Safety`, so I hope someone will
look into this before merging.
2) In those places in e.g. AD where …

Support for Unsafe UpdateAcc

---

rts/c/tuning.h

Perhaps there is a good reason this was not already featured -- in which case, feel free to reject -- but I find this nice-to-have convenient, rather than having to delete or move unused tuning parameters.
Can import `isspace` to catch all whitespace characters.

Allow blank lines and comments in tuning files

---

docs/usage.rst

Hi, I found this typo when going through the online manual. https://futhark.readthedocs.io/en/latest/usage.html

Update command py to python in doc

---

src/Futhark/CodeGen/ImpGen/GPU/SegRed.hs

Found another one. `blocks_per_segment` is already `sExt32`'d a couple lines above, so I assume this fix is fine?

Another ImpCode int type fix

---

src/Futhark/CodeGen/ImpCode/GPU.hs
src/Futhark/CodeGen/ImpGen.hs
src/Futhark/CodeGen/ImpGen/GPU/Base.hs
src/Futhark/CodeGen/ImpGen/GPU/SegRed.hs
src/Futhark/CodeGen/ImpGen/GPU/ToOpenCL.hs

On our current backends, an atomic write is just a write followed by a memory fence, but on some future ones (e.g. the WebGPU one), fences supported only implicitly through use of atomic data types. It turns out that in most (all?) cases, we only need fences for these "atomic writes". The possible exception is single pass scan, but we will not use that for the WebGPU backend anyway.

Replace some memory fences with "atomic writes".

---

CHANGELOG.md
docs/language-reference.rst
src/Language/Futhark/Semantic.hs
src/Language/Futhark/TypeChecker/Modules.hs
tests/modules/ascription-sizelifted0.fut
tests/modules/ascription-sizelifted1.fut
tests/modules/ascription-sizelifted2.fut

This is not really a "fix"; rather just codifying an existing limitation. It can be lifted later if necessary.

Fix #2120.

---

CHANGELOG.md
rts/c/backends/opencl.h

OpenCL backend: pass -cl-fp32-correctly-rounded-divide-sqrt.

---

CHANGELOG.md
rts/c/atomics.h
src/Futhark/CodeGen/ImpGen/GPU.hs

Based on the technique described by PipInSpace at
https://pipinspace.github.io/blog/atomic-float-addition-in-opencl.html

More efficient floating-point addition in OpenCL backend.

---

rts/c/tuning.h

This PR now allows completely blank lines in tuning files, by correcting my own mistake in which I had neglected to account for `fgets` storing terminating newlines (if any).

Add missing newline

---

CHANGELOG.md
src/Futhark/AD/Derivatives.hs
src/Futhark/Analysis/PrimExp.hs
src/Futhark/CodeGen/Backends/GenericC/Code.hs
src/Futhark/CodeGen/Backends/GenericPython.hs
src/Futhark/CodeGen/Backends/MulticoreISPC.hs
src/Futhark/Internalise/Exps.hs
src/Futhark/Optimise/ArrayLayout/Layout.hs
src/Futhark/Optimise/Simplify/Engine.hs
src/Futhark/Optimise/Simplify/Rules/BasicOp.hs
src/Futhark/Optimise/Simplify/Rules/Match.hs
src/Futhark/Optimise/Simplify/Rules/Simple.hs
src/Language/Futhark/Interpreter.hs
src/Language/Futhark/Primitive.hs
src/Language/Futhark/Prop.hs
tests/ad/negate.fut
tests/primitive/f16.fut
tests/primitive/f32.fut
tests/primitive/f64.fut

Previously -x was defined as 0-x, but this is wrong when x==0.
This commit also consolidates numerical and logical negation, so there is no longer a 'not' unop.

Add negation as a primitive unop.

---

src/Futhark/Fmt/Monad.hs
src/Futhark/Fmt/Printer.hs

This moves around the uses of 'fmt' to be explicit in the printer itself rather than in the combinators. I propose this as a more explicit design.
The one exception is (<+/>), which I think is a symptom that something is wrong.
As long as Fmt must be an instance of Located, then there will be bugs.

Use monadic definition of Fmt.

---

futhark.cabal
src/Futhark/CLI/Test.hs

An example of what this change does from Debian's ROCm CI: https://ci.rocm.debian.net/packages/h/haskell-futhark/unstable/amd64+gfx1034/39652/#S12 (from line 2354 onwards).

Call abortServer on test timeout.

---

src/Futhark/Internalise/Exps.hs
tests/range0.fut

This PR is similar to #2194, which ran a little off-topic. I thought it easier to open a new one with just the pertinent commits.
There is a discrepancy in certain cases of inclusive ranges between the interpreter and the compiled backends for inclusive ranges with `start == end` and negative step. In particular, the range `1..0...1` gives `[1]` from the interpreter and an "invalid range" runtime error from compiled backends. This PR assimilates behavior of compiled code to that of the interpreter, for this single case at least. There may or may not be other discrepancies.

Fix inc. ranges with start == end and negative step (2)

---

src/Futhark/Analysis/Interference.hs
src/Futhark/Analysis/LastUse.hs
src/Futhark/Analysis/MemAlias.hs
src/Futhark/CodeGen/ImpGen/GPU.hs
src/Futhark/CodeGen/ImpGen/GPU/Block.hs
src/Futhark/CodeGen/ImpGen/Multicore.hs
src/Futhark/IR/Parse.hs
src/Futhark/IR/SegOp.hs
src/Futhark/Optimise/ArrayShortCircuiting.hs
src/Futhark/Optimise/ArrayShortCircuiting/ArrayCoalescing.hs
src/Futhark/Optimise/HistAccs.hs
src/Futhark/Optimise/MemoryBlockMerging.hs
src/Futhark/Optimise/ReduceDeviceSyncs.hs
src/Futhark/Optimise/ReduceDeviceSyncs/MigrationTable.hs
src/Futhark/Pass/ExpandAllocations.hs
src/Futhark/Pass/ExplicitAllocations/GPU.hs
src/Futhark/Pass/ExtractKernels/BlockedKernel.hs
src/Futhark/Pass/ExtractMulticore.hs
src/Futhark/Pass/LiftAllocations.hs
src/Futhark/Pass/LowerAllocations.hs

This pull request reorders the argument order of the SegHist, SegScan, and SegRed operations such that the kernel body comes before the operations that are applied on the kernel body outputs.

SegOp Argument Reordering.

---

CHANGELOG.md
prelude/math.fut
rts/c/scalar.h
rts/c/scalar_f16.h
rts/python/scalar.py
src/Futhark/AD/Derivatives.hs
src/Language/Futhark/Primitive.hs
tests/primitive/acospi.fut
tests/primitive/asinpi.fut
tests/primitive/atan2pi.fut
tests/primitive/atanpi.fut
tests/primitive/cospi.fut
tests/primitive/sinpi.fut
tests/primitive/tanpi.fut

These map to intrinsics on OpenCL, HIP, and CUDA, but are expressed in terms of the normal functions on other platforms.
Closes #2243.

Implement pi variants of trigonometric functions.

---

rts/c/scalar.h
rts/c/scalar_f16.h

The conventional style is too verbose when it comes to navigating a huge amount of trivial functions.

Use more compact coding style in scalar.h/scalar_f64.h

---

src/Futhark/AD/Rev.hs
src/Futhark/AD/Rev/Monad.hs

This changes most of the UpdateAcc operations emitted by the VJP transform to not have bounds checks. The idea is that if they worked in the forward sweep, they ought also to be in-bounds in the return sweep (there are some exceptions).
I don't fully remember why we had so many bounds checks in the first place. I do know that we had them in the initial design for commonality with 'scatter', and it is possible that we never went back and thought about whether they were truly necessary.

ad: fewer bounds checks

---

rts/c/atomics.h
rts/cuda/prelude.cu

This defines the types such that they are compatible with both NVRTC and offline compilation with `clang`.

Make CUDA device code easier to compile in offline mode

---

src/Futhark/CodeGen/Backends/GenericC.hs

The variable name of the argument of `futhark_context_free` in the header file declaration is `cfg`, not `ctx`. This is inconsistent, and this PR fixes it to read `ctx`.

Fix variable name in C API futhark_context_free

---

CHANGELOG.md
rts/c/atomics64.h

The fallback case used OpenCL atomics by accident. Now it uses our portable wrappers.

Fix f64 atomics on pre-CC 6 CUDA GPUs.

---

CHANGELOG.md
src/Futhark/Pkg/Types.hs

Allow the `~` character to be used in package paths so that sourcehut repositories (e.g., git.sr.ht/~user/project) can be used.

allow `~` character in package path

---

CHANGELOG.md
src/Futhark/IR/Pretty.hs
src/Futhark/IR/Prop/Types.hs
src/Futhark/Pass/ExplicitAllocations.hs
tests/issue2288.fut

There are still some quality-of-life issues regarding memory aliasing (perhaps even a few obscure bugs).
1. We do not add information that the memory blocks returned can alias each other.
2. On the other hand, we let every returned memory block alias every argument memory block.

Fix #2288.

---

CHANGELOG.md
docs/performance.rst
src/Futhark/CodeGen/Backends/GenericC/Types.hs
src/Futhark/Internalise/Entry.hs
src/Futhark/Internalise/Exps.hs
src/Futhark/Internalise/TypesValues.hs
tests/sumtypes/irrefutable_case.fut
tests/sumtypes/irrefutable_let.fut
tests/sumtypes/irrefutable_param.fut
tests_lib/c/sum.fut
tests_lib/c/test_sum.c

Another solution would be to change the representation of unary sum types to not have a tag at all, but that is more invasive.

Fix #2314.
